apiVersion: v1
kind: Secret
metadata:
  name: cert-manager
  labels:
    app: cert-manager
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cloudflare_api_token: {{ .Values.cloudflare_api_token | b64enc | quote }}
