grafana:
    # sops:enc
    adminUser: ENC[AES256_GCM,data:REKssVvjE1E1vYhH,iv:PutgQHZsOYEDt8hsRaJefhywtBoijBuMRN4wSlAn3Ko=,tag:Jy6S8+MXNZLgJP4oXS4ZwQ==,type:str]
    # sops:enc
    adminPassword: ENC[AES256_GCM,data:LZ9/fXSBiOB8XCIRi6sbM4MuTI8Q7z0TXVrAjaJCCu8=,iv:Z13nPKsy5p9XcWu1FEYfRUNJvOucKDrY7rAJ2RCRkKA=,tag:nNn3AEWxaR8wIPzmlArbww==,type:str]
    grafana.ini:
        server:
            # sops:enc
            domain: ENC[AES256_GCM,data:fNvJ1rnlErcpO80qwCabF/33dCHEQw==,iv:lsjjn3a95qZaVFsWaK6AoM/Pkvs7n6cF9tpSLq85Xr4=,tag:DkSvIwUV5/S+ysCcaDuCXQ==,type:str]
            root_url: '%(protocol)s://%(domain)s'
    persistence:
        enabled: true
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            haproxy.org/forwarded-for: "true"
        hosts:
            # sops:enc
            - ENC[AES256_GCM,data:M+k25SbXcRJ9ahVyrATVLaln6AK+3w==,iv:FgLkjfNgzSzp57K2fgtUtIkkLWaGnK44A7lzlVfk5/U=,tag:r4w5NRs8qpU2FWESV7mNRw==,type:str]
        tls:
            - hosts:
                # sops:enc
                - ENC[AES256_GCM,data:G3NJNyOdKLWK14uKGenHm/EKDDNeew==,iv:qOB9qX01HQmYGiNmqfIQgtTq/X0ST+hmbjClaQ9X0bQ=,tag:/IwaMMrc4rv4vQNyvIaEBg==,type:str]
              secretName: grafana-cert
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM2M1R0crNm13cjdwZW5M
            czMrT0RCeE9YaFB4cnRXU3Z3SDA0VVZtY2hRCkE5dGU4UFd4V0xDdkxPbzlDRmpW
            aTNVanEyeEMxejBwSC9OMS9RaDljU1kKLS0tIE5ydEx5bkFKN25VbWRXQTlNTFlL
            WmlXVWZqbzNFeE1qMVVyWnlRNmFjR1kKI4VPg29htHjSeOwpGWcM+Q6tYG7AP75H
            YI/J/9gvwj2L1U44astDVKIlpvYWvjaam2eaLEOcCEKgOFsf9zWo+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:35:10Z"
    mac: ENC[AES256_GCM,data:tQy0vmz8d2Qxs3Rmm7hyfxVuTa/z5lpzJDJ47KrAaKu3vjaA5pJFGsGYXVO6obJMpiDTQIcYV7iNRDb/TBG2ZJghU8ktI3/lCglQ7WSbVDG5Fe4Fd7RolBy1EOkCAfIkysMu+syPeaIdWlyxCt/8ITRvaCNawIT5wXD0db9VCHs=,iv:VqWdp1CMbzhr1AI8LdCJ5+umZZdkS1OdKcYAnxITLSw=,tag:XHtB3sUxNLHm1P77YPQpqw==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
