grafana:
    grafana.ini:
        server:
            # sops:enc
            domain: ENC[AES256_GCM,data:5HcRJ4rzdl0lSMuuXFvtKBRCLCHhZQ==,iv:wFTw6EyHHSSRM2Lp3E0BF0aAHmwYrH5J9Ja/phiLoB0=,tag:oiSLtJEw1E3jvvR1kU3UJQ==,type:str]
            root_url: '%(protocol)s://%(domain)s'
    persistence:
        enabled: true
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            haproxy.org/forwarded-for: "true"
        hosts:
            # sops:enc
            - ENC[AES256_GCM,data:DN1p89bmwuRpHOFl8xEf6w9CaVbfPw==,iv:Ivt3j0LsdpBMtkEkRI0JvvUsiAck7VUXVPmXfhSdVLk=,tag:gT3vCmr4i5ll6mUBi08rnA==,type:str]
        tls:
            - hosts:
                # sops:enc
                - ENC[AES256_GCM,data:hoKDlWb5f4uwS4LmGkGN/f+Zdi8nog==,iv:q5Sd85V8BgdC5uOWbgzAgxZweWVjERxYTnTRelkt5ss=,tag:7hdNj7DYobMJ30dLO/USLg==,type:str]
              secretName: grafana-cert
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNEF4eXdEMTc0R29zNE9t
            OHNaSXNHZ1hoVDJ4T3NNajNISDU5TzlKdWdRCmNxVzEra1hyY3FHT0NPUmplNHB0
            ekFUOHBpYkNZT0pFdENCUFhLRmFydk0KLS0tIHpoTjdTaG1KZzBqU0l6a3dzQjUv
            R1FXVmNrdElpb2ZGU05sZXFvRlh2NGsK0FYXnSM26HTVSz99Ndo8ISWatD2YUDS2
            zzwaTwPyA7KK5Ty58hoGPAbItOaUryi5yuyP47DxrFw3SXaj6b41RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T19:21:53Z"
    mac: ENC[AES256_GCM,data:kAHM9/zYL/X19bIHFfe5HEnSSuJ+ICTCP6vX21vhsQto31ljof9jp9rQ1kamV/QPecSQSsC+vzfbCIEBC23OcGcy3kSTVXYwSnsN5fuD+hPgDVgPoo6dPQWBt1zaIXa1Ysfe/zsgO2q/IsNE49KHUkLy+3UosEhryMKWBMPmjf4=,iv:phYwpibjQ0hrvLIloXhV5PvWHbM9e4GKCdlmTAB7+BY=,tag:Ey0Xcr1sKpZkM2g/S0oxFA==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
