grafana:
  assertNoLeakedSecrets: false
  # sops:enc
  adminUser: ENC[AES256_GCM,data:P8RwJ0v4t5LcL2mA,iv:REOdPc2i3Gr+8Xff2uTF6VsQUj84179i4Ng7aUp9Smo=,tag:TpEYdl2nc5wufBWbUtCnPA==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:YV9H3GsUd+McHnfVsWvh6nglF/odGoZ+jV3Mei/HhY0=,iv:i9mlS/ej9zadOsZzoGVTIPDu35oxePoCrqt+tq36Bzw=,tag:RCCLPru7caBB5oArK207oQ==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:cG6Iq7tI8BzhwAo1AmzKZnAgNJoRCA==,iv:Fz7KkzVAxi1hggDmBYvk4BSo2+Xl6Ip7xq3PktVrwUA=,tag:fDPb6J1PhEZ1qW8/Z4nkRg==,type:str]
      root_url: https://%(domain)s
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:EDrAyA==,iv:Uuhjjy9JJxTQzEYU02cvZZj54XY8It/iji14AF2pZ6g=,tag:8Loqq2Y8oHoAEleQAifr8g==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:t7hSEg==,iv://7T2xINZWpRavGA+A8ePKkCGCpXBhA3x5GjD7Vbm24=,tag:QZ0f3g9BNUv9K3Evb4NoAQ==,type:bool]
      auto_login: ENC[AES256_GCM,data:vI18KA==,iv:6scNkECW7A13DKlAoSdrDKGRBTJ1BuA7RQcnazCqL1s=,tag:PrRY3gwo07CAzh163Gi6yQ==,type:bool]
      client_id: ENC[AES256_GCM,data:YtblroxgxoPFSYUMqu5KsU9JJ5vwuC0WxcDRj1OQRwMFVzvDTPKPsbn/Pvw5VQXgn1rh3IlAXhUpfwjGkQHlFb8MK4lcLYEv,iv:0R1U4oara9eZ2y/6k1hrKBSwO4ustA9DKG9HzDLHnL0=,tag:tyRxD6C9pLnULCEuROK9xw==,type:str]
      client_secret: ENC[AES256_GCM,data:ZFWNn6ZXmHdVs6/OG7cLMO/SeK6axr/Ccklr9itiN6eNgME=,iv:Vhe01HzWyHTkV9V8yUz335HpPhqVNe+h37Q9MLXaNmQ=,tag:rdxUMf94OWDjENqMNE65Dw==,type:str]
      scopes: ENC[AES256_GCM,data:RRNpjeRfyEEuQNS8Yg5HyNVSqLLQD5aghyn+bunzXhb/Vde0nBULs525MwWgEN7DQChJd0hdsv5omKcYYoho5WOQbf8hfCs5QMjF66cHRc3kV84=,iv:TwKVqExuhXPCXMsvm5M+2CAoOBXa061wGLACKU/B+Y0=,tag:dZ8ZUxKlmpH3J9iWG3MoxQ==,type:str]
      auth_url: ENC[AES256_GCM,data:hWdqE4qQNrfFGlKyJ3Vr0hlfPpdqT7Y83QYJMev9SEITbrPXgOKnKP1emMo=,iv:TgSXko7OWqJp5H2PsQTZmEp7TGRCGBPX4c29AcGxLbo=,tag:3dgoFx7sEDMCE09C0+xflQ==,type:str]
      token_url: ENC[AES256_GCM,data:xJf8eHdsToGZInldfhbxnBl73iyeDc6tqG1oHrFKQues8jw=,iv:8/0DtSf7Qnr6e0nlc7FTRgr0YLEteEld3FtKZLi40Hk=,tag:UwMAX/cX1w8LOQ69edgp0A==,type:str]
      api_url: ENC[AES256_GCM,data:dbceD5eXFdq72H6hi3TCGCMad3+Y/Hx2bsGLU922q6QlCmViiIy05LsuJ52fL+md,iv:GrSgklWPEdlhVeMJ9phbrP5e12IszjlzzSll/xYW6ag=,tag:T/ZZjLGjMqZGvbR5Pgf31w==,type:str]
      allowed_domains: ENC[AES256_GCM,data:sw/avfsALmxaIjKT,iv:RBYN+EOBSipZH2H72s+8weyIAcEGdOCPzqJ7fpvBcZk=,tag:BZrOXABPmRiCzIpVB8mmCw==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:6cJekSCXEfzD+kyjqMtnJh84jRNuLpcnWqLjEA==,iv:QNdhYg8BmMDABNiFNy0NNylSF0s/KBs2PoA+E5IFzPk=,tag:AgahCceov5JZleczyWqHYg==,type:str]
      hosted_domain: ENC[AES256_GCM,data:UwmgKE8FaMMs7BY8,iv:3YtK8cISStQuhWgabZwsFf2dmhXecoxblJafMcTafJg=,tag:62ptycSg9Z/noMfdfBlYTQ==,type:str]
      use_pkce: ENC[AES256_GCM,data:FKfA5g==,iv:IIIUGkAqTy8KkjHKnq6WdKT6TolbygiysrZM6ol59tM=,tag:7Xw7t1i/NLX6Q6lkoVvAyg==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:HN7HS+9ylqWYyTIn+5PFfRnTPYDNXg==,iv:KMbEoRm1Y7NeqK4I9KNcK5GoitmXVuG+5XonDYeVRgg=,tag:MOf98ZPVY/pedkXfOGgxlw==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:YNI0OtDJQdHRB1OlidJZJ0ea/7USQw==,iv:wioYI2C8h7W3J7B9O2uwF/1/JEkgLzww6cp9rPRRLO8=,tag:/JsM8Hu+YTS0Wqz/9FGDJg==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN3oraUhBMnN4R094QUxr
        QXVLcWcrVGZ4Y2FlR3NaYXp4aUR3T1ZGazFRCjR0OEh1c0hSZ0x5Rm5qckQ5Vkha
        UUYwU2plSHpIT3BsYjJuZGd2VDF6bGsKLS0tIFR1TEo0Zk8zczMxaWxNbFRuVUto
        Z3c4WmRDUy9mNmF5SEtHYXptMEs2cVkKaGYZcXBi9mU0l5K32P5XeP191TXtF8u6
        1h5z06F06pUj44D22R6Yn+91lYHcFlU1y08z1nHtIU2mHFC5/NkV9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-31T17:10:22Z"
  mac: ENC[AES256_GCM,data:WiJLDpY9/LYKWwyXb0bMgpMv4CW+RFs2dJezc8/rFiIaydp7ih17rrSz5sMTNeRrIgdEqlW04MWF5igZlaaJKMFSC5j47dBVdldbyj7hXDZ+BbXKiBcEm14JhmuJ9G7wMWpDD067Hx7cQLGXHKTA10jyI10vBrSSqUYh92zpoEQ=,iv:7KPyquqWsEPO1lv8GnTN7yv6KO6b9XLB5uJj6dEQrAw=,tag:dqWWSiohqLInONvNGmUeUA==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
