grafana:
  assertNoLeakedSecrets: true
  # sops:enc
  adminUser: ENC[AES256_GCM,data:LAYXjCcIH42u1Dyx,iv:HiUuxhMVsDiAHotRcbaTB3r8xFJe3nTgp/gHucrj4lA=,tag:vuKJ+I73f1FHlHF4KXRK8Q==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:hEKMNNlCgxJvRwXHQlvO/5LbRHSwqvoRC1enlNRy9Ks=,iv:8ugyn0asFDu0BOk2Bmpp/HxZadmrG4u+lurwFieTzlA=,tag:c+ktK5x4cRXfFTdd0j6FQw==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:6q8DtzOYQPVYe13QHxOJBA6ZBnkNfg==,iv:M82TNuri8s62nFCHE+ZnGeKDiHN3ETllEsub2YpdX08=,tag:vRaVbnJl4gEMctXh7NH/AA==,type:str]
      root_url: '%(protocol)s://%(domain)s'
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:dU6yzg==,iv:IrjSELZB0RkztFJLMUgH6D5VZFHckGv1qsr1rA3SP14=,tag:5dcp3wQfyeV/59T8VijTCw==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:1KtwgA==,iv:86cwJVucBzzT3obCOKtfNtyL2FaPkbyXkeaoV8IsJKs=,tag:+YszfHcKSq5UGen5SI75Xg==,type:bool]
      auto_login: ENC[AES256_GCM,data:Gcs6lC4=,iv:8Vbjx82zgSQgRnokstXNs8JaBTlVVeVG4CVWLkoXS9g=,tag:bIn699C4RfnXe8R8ezzkaQ==,type:bool]
      client_id: ENC[AES256_GCM,data:09HhuOMBene5ZpO+D4xU8PZLsQerksUypJ/sdxdw2xueE39TEUXzx8tsWCXPqEWXN64cIg/oKKvKbrPXY15ZWiRTMc8Yukty,iv:fSGxwLrrrKFFxlbx37TcqXJ04OJGfbu6l5GaqgeVfOc=,tag:uc4mzoY8feqDvcC2ijLbdg==,type:str]
      client_secret: ENC[AES256_GCM,data:lZr6Pxdxm+onQPqx68eWvgS0xEp1+Lwc1h4W1wizcavQAEc=,iv:zDuXtmlF3L99C5x8iDBr+AJ8WJSP+Zq3bAQoAqEIYZg=,tag:sbvcYvJ7rclXwzdLiuOX0Q==,type:str]
      scopes: ENC[AES256_GCM,data:Ae5tshkHdjy3VCQ8y1gRP7sFdgswVpGWtAHab1YexRHNku9QLPRiH4tZluUafzWaKP0fi5GloD3tMHeb0uTYm1w3hFInLgWsIo7iedTpbir5Q84=,iv:l+v4xcxm9AcHNJx4If3zlEePtS4PEDQxoXhngObCDTM=,tag:OZ5u2P7y1qrKGZ25ZPd0vw==,type:str]
      auth_url: ENC[AES256_GCM,data:Sx18OYuF+rQfVrlbNG/+IfZ1bvIs0lCiK1V5ziySjX0vl1HLFYlV9QEK0Ps=,iv:O8Jt28aUKS25fPWHvIzO46fsNbDPn6lUlPJOi2CgoUk=,tag:UknODpRBUhpjAn0KqGuEgA==,type:str]
      token_url: ENC[AES256_GCM,data:Y9wKdNQgZhrlfozTRYXi30crbpK3YUs4KJz6eigEfyrutVE=,iv:HeC4/fY1XADjQEuX+y780CZx6bs+VdgtUtyKNI4FVlQ=,tag:1HWbS8dX2gyIgp3LHehKzQ==,type:str]
      api_url: ENC[AES256_GCM,data:XGNwnMzEoXrLoOJGF0q6eDmfLx0dwdUgjcMOBO0wLFKxAXYpcZSasto8oRTTesiT,iv:u/TrDz/esVbfp0chnwpLVPaJv1vG6Zcz6LBL+OcXP0w=,tag:1DPebuFqI2/8v4zSG9fd8A==,type:str]
      allowed_domains: ENC[AES256_GCM,data:+P4/z8WR+S/COXWp,iv:aAtG8DrCPASEZgGam/3u5xV3DjTB0c6eY0HXpCqVHYA=,tag:pk9fk/FFN+Cf0IWkmIgwpg==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:J4DZgTLLFtMnjt5oZrnBE+PYh7zvlzzRPQuC0Q==,iv:LDfKEPvrk2MzWe6+0xQPnGvOAwnV9zt6lYhJ7WAK5iA=,tag:ydmcyDxI2S+b4+6flChSDA==,type:str]
      hosted_domain: ENC[AES256_GCM,data:Y27g+sgxoyFDoP0r,iv:I98nxdSflfFHTz4g5kWkmMJe7kXPlyX7B/nV5G3S+mw=,tag:pr481AZBB0BvSigtNln2bA==,type:str]
      use_pkce: ENC[AES256_GCM,data:yATHFw==,iv:2LPHT1FQGslKwYqqXdtB+iJft7rCJQYPs9vzELsvkYc=,tag:6/XYaebo/HFiqjvYm4BJHw==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:Ve46sdcbF/rEZDpOJXoBYPZbMk+SiA==,iv:KEqUhO5LTflKdf06FZsrYO6Lh5ECrK8ud7oeQTdZ8BU=,tag:Klz/vkyBC6USjskvA3ykHw==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:FMNK9OhoNw/Cd1goBP6PBlPy1akgnQ==,iv:Krcoydj+SsD6exjJosr8Sp+CgJokzSA64l4oiMHiMoE=,tag:wh1gXIDRqDf+aUXaogyrGg==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMDFqS081Nm12RXNPMGNp
        MlBDa1NyMXpwYWw0b3lLcXRVUzFmR3dGTWpJCnR3NE9mY3Y5SnpJSTIyRmdDOEFs
        WUs4WnJORGxTOGFIVHRUL2ZOZHVRYW8KLS0tIFZMaU50OWp4bVFhQlhjVTRyRkEw
        Y0pzWVJOalhFZUpoNC9VazA1ZHd5czAKaHNRH5QVgYh3jNk4TWes+7tDmSN7+6gC
        eO7zrHiZx4y6rKgp7mpbPYw4pyKvVMKmdnQ5OiHbxtTU1Oq4k+Ft8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-20T12:31:33Z"
  mac: ENC[AES256_GCM,data:obs/jOaSiCBbW7JAd+BGJKoSSVAhWpaNRzETvbLsK8HYTothfCCMogZ7w8Pi5SITvVI7HeZtr1RW4UfxOPcIugc6f+1maffKGEiceoJmLNVDHoyFwcns9DZa58f2PfB8QHu83FCuj35sEC444P87Mw6sn6/I1FOidRlIIotwD50=,iv:uVftGGJ2YZqr7oS3nrlm5asJBfTtrvdcufBDDVqG6K4=,tag:1h00qGxBD5QmSrSEmQVpQA==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
