grafana:
  assertNoLeakedSecrets: false
  # sops:enc
  adminUser: ENC[AES256_GCM,data:2LRJ1g0NU+/kaINC,iv:pgQOlMsEc+fqKLhlj9dDbfzDCGyqdPFXXtwqueqS470=,tag:ZFWwzxtUNxMhOfBElEhwMw==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:Jzwu/qj9+aZgZxOhIH4wnazbg4S5mOVLrN+5eBvVBOM=,iv:F1u7jnHexf2bmCP3QRZWz7Og4fPhaLRxmi3/wQgboVU=,tag:jT1XXRwa0o7zLiq52eiByg==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:Umbie9pe9tomzLjMHm8lwlr3WyPaJw==,iv:kiKKd+b0xQSDb3Lsnf6PG0ho338Z5JWcA37/ZGOk6CE=,tag:xUhpXpJf/SEbyEHdGSkb0Q==,type:str]
      root_url: https://%(domain)s
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:Ol0Yxg==,iv:r5bzOIXcQjqqVNbuEVFrMScAZf4Z8iICdrMbLTSAFNA=,tag:7uuickDf3t25T2amXIpc5w==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:qI0bPQ==,iv:ajUvFuuTqqsP4ZzADs7aO50BaEkN9g9+QlvjxB1mZRE=,tag:7NSYM4VP+Bl2Pfbz5UT5QQ==,type:bool]
      auto_login: ENC[AES256_GCM,data:k+0pLGs=,iv:8Z7Hz5zbynbWFDBNax8OtuAAWMlwq4xm6R1ZB7FyNNc=,tag:tmqVxsHlC8ICWvSp3tTbaQ==,type:bool]
      client_id: ENC[AES256_GCM,data:B1T5FHRTOi1fzIr9gwaDJg9iDFHvgT194OP7ckuJRFz6wBAMERNA1LYo1f5QIqYU4pKzW9ZSdl8nDsJ9e87BcMgHnk5eScxd,iv:KTQc6YbGlRhlhPyHTO46kxMBr/EpY1+dnIiIF416Tps=,tag:ZldaV+hxhgWTIG815QZS+w==,type:str]
      client_secret: ENC[AES256_GCM,data:RTu3Od/5hMAkkfkF2txt72QIlMyxLiAtReRc7VibOfh8ovQ=,iv:gO6HJ6uma9fUD7nYVyLocppVAKxJKIZI2c4h7wyHSOE=,tag:aoafLubkdzvQhOcZbDvwoA==,type:str]
      scopes: ENC[AES256_GCM,data:+ymWaiJM+MyzQo32APfDNGhD8mu9PbhSWBQJyiklwSZr2yiYSHA4VrNtFt80J2Nohc0UuiuJJGtBR4FTXiqDtj22Fpda+enqjrU+Ovyg3qfnIF0=,iv:8BI+8UxAeAKSdPCvgdoPsVBKPdjys4EW1MecdWDCUPQ=,tag:N0nM2W/GspGLL2PDzS3fWQ==,type:str]
      auth_url: ENC[AES256_GCM,data:tfp7SxKjkAIR30WQwqSfBn22ofVdLvmCQUfm3dca6gnDzMX3VOloP/Bqq9M=,iv:82m0MMOp9rjMZX+Hi4/imUDBAEUoqt90wZcWZ+mGU7U=,tag:V7/Liyz293ASHVjmCidFQQ==,type:str]
      token_url: ENC[AES256_GCM,data:F8vH24eTFKiBVjI+b6mjXlfkHNRACb1ozMgsQItEc7fh9K4=,iv:hX3QTdG0eVxCGU0gQTc9wL8vWUVdWIx+RkEFsHPe4oI=,tag:g2MdTEidMpiRlrVQSyioTg==,type:str]
      api_url: ENC[AES256_GCM,data:gXPu4/l9ZDaxnNNKVn7Bhi4SSUXnY5PV2mCKUTnREPwfYIGqJ6T7bR6eUdcVY6P3,iv:+MLO/yZPl7+l/aRkCX0tEwqc6gYzHrxFy7zFOabtZRc=,tag:EvwLtVVKA98uGcdE218uJQ==,type:str]
      allowed_domains: ENC[AES256_GCM,data:6cwc1BDHNN2uEOJU,iv:xQf3c1L2W+gSFEwCwbJQDQxaNqXOv56u0azPznbJA/Y=,tag:k7nVoMXndOTl0Yaixlj1lg==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:yHNHtKj5s218uq21G4VxN/X/jrCYv+Or3tkvEg==,iv:GuqnQdrshcENnHKmRUVY5vcscPF0guLMw1bPRlwads0=,tag:7phOOwWBRzlW1CdDGjtskA==,type:str]
      hosted_domain: ENC[AES256_GCM,data:tAeV91JeDf1zvseS,iv:W0QK4gp7JtaORNXeCerlDZxCLVT8xzeA19L6ihQrMJ4=,tag:25wiUmanLto/ykY+C0dvXA==,type:str]
      use_pkce: ENC[AES256_GCM,data:BUzGZg==,iv:wN3v8z/SmOmqXv0jfMOst3leJMk11MPI4qbPu0pHgPI=,tag:SlsurYvSzOTb/mejSU/q5g==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:1Ilzuyqed6I5B3aJJRG73YdCbBEkyQ==,iv:pvZnH3Gq9jEqgMF0CVzArEO/PmcVsWAb6eH71eC5xgg=,tag:zrO9eFn2CmMYE8kOq+V7Tg==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:+rUtZp+S/RAJiwvDiK85Vf5yepbLAQ==,iv:LiGmTheRqi0Iv6Zu9r/k4eKNNNpuDYEY7R4fzlKXHug=,tag:JRq04m8MAPsv70CrDnI14A==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dnE2VVNWZkl3cUhpVkk2
        TDFkcE54cXpuYmNaU0xIbE9YQnlpM0JzRm1ZClViN2o2eVN0UDhOQkRFVkk1RzFx
        SHI4ZU9nTkZTdW1Fck1DelFlbnhPZVkKLS0tIGpOTG85RHBOcTFCTXJKRzdET2JJ
        d09QWjZUMWZKUkFhaEl6L29hWjF5Q1EKmIqTcEoLy+BOVK7lpJPU3p1nTM67kLhm
        VkJgT+kgksK5DoYxok+M8Gw2LojOnEierBJLQeyG5CKlN5aUCnbzqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-20T12:38:10Z"
  mac: ENC[AES256_GCM,data:VdK7QxGjA/mwJ7GmmS8EV9vgwg4YiDoR2CVQMlPHAGYJg6wkwB/CpQhlqzkM2FyQHVzBNQvzcxAvyACTKO7ojj8ihAycCrj0NHEM6XkRkrGNoQfJpOGNbqLHjoaGTWhu6+TS2s/kkOFLQ/JyZtq0v3aXRRo0nCaIxxmTHMP0nLE=,iv:yn/42Y7eH9q/9PzRSovcf4g1YL4QxqdMJJUH1lDspiM=,tag:RDp1XaO/8VmBQxaVM5mrQA==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
