grafana:
  assertNoLeakedSecrets: false
  # sops:enc
  adminUser: ENC[AES256_GCM,data:PFhTCdv/k0r9HYCx,iv:UxDqgChlGXfg8VJyXNYuF2L7FFokpDnR8OnQriT6FHE=,tag:VyMVOQTDkXhOSQNwbbz13Q==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:tKcab8U+dtexBmWPZboMO02TQuTMukfG4avdori+3jw=,iv:b8YgohBk2q6V4/FhUQp3GCFGi5XpdOFTLRF5qTUQDDg=,tag:WkP2Wtl3Zzx/zQ8pHl15AQ==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:8uwDK/LYESyF9mE5vPFvRqYJg9Mjuw==,iv:N51eI1GpQkfUIfkElgyWCAJekpH4RFSrbEZwJMmrYuE=,tag:0VHhOFbj13QKwnWb6zWy8Q==,type:str]
      root_url: https://%(domain)s
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:nOdLdw==,iv:qGIg51wg7zJixP3BT6fNvGKwqpEhDdryt8R0Z9TIyXU=,tag:P6CgNd+uZoLQtjjliTMo0A==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:Lso+fg==,iv:iJwj+mrCstOdiSaFJ3yFAFRBgO8+1GT89pyKrUFn3p4=,tag:ixAK9GHyvKJfPY5RTKGQTg==,type:bool]
      auto_login: ENC[AES256_GCM,data:DPhSpQ==,iv:OX6tr39HfAaaf388r4eTAcxplIDKNMrTaTtGzcQVSZ4=,tag:fmQe0Af39otrryI3YCTxlw==,type:bool]
      client_id: ENC[AES256_GCM,data:u831keJQP9OChYtXBsvNFEH6Za9e2/lYme3Uz3f6xZAAwbO4dR2oTz7nesZMO1fMKc5JqcUF6SY7tAJOZ7aumqXB/+BO18ja,iv:NbfRicAOl7gg+ai7JIYCA6B/r9zwfOUDtQ7s4DDGxyE=,tag:pC49NGX4uvreJGOzw2W0HA==,type:str]
      client_secret: ENC[AES256_GCM,data:oitxOhc9Ao5YAxk9CW+1HlTfnmNkNjQGTSDmuU369DCYH/Y=,iv:clGqcINWuw8IQ19jMzHEndQWAufF+3ynaUSh0a/Eoew=,tag:NW7NAHQCNnpY5g7iAC8DFw==,type:str]
      scopes: ENC[AES256_GCM,data:0yknHR6LTVh+PczhQZUXKsuZi8kuQwcJ2cAveO2CGCLv1zXCRrQ88oycETtQKyohxsR0kAX/NbgN55+wuyg5womHeI903nWviiPwLJARuaxMLCw=,iv:3fwGp/N/uobaJeN+dg2wqPXc7uV4yN2msila0zZOGHI=,tag:2E4h15EhGRdJkfbbpRchbg==,type:str]
      auth_url: ENC[AES256_GCM,data:oqYYtCC8TIW3AIL+nuxhA+dZn3PTtT6xbzdzPJylQesshzsH3BgSEqfnIng=,iv:/oOxU2/oBY+aq/dKKSwYkfvzNX/xS+kNNXXw+n+xITw=,tag:WY/wU3uVsBX4yngpJYlogQ==,type:str]
      token_url: ENC[AES256_GCM,data:Cd3bYxRzJCSBSc/LM4JZvo3/myr8EZRYJFSyjn1keEtkdPk=,iv:Lt/BPxA2xT1CPUYtXPPkN1SM4IFZ+TRZqelONWlE62o=,tag:gjU+gQvVo4AxtYPCS+MLsA==,type:str]
      api_url: ENC[AES256_GCM,data:wjvFVGBkXqKvU39/k8pK98SkcRL5T6fsj697xHCpR1D1nXXKaF2SvKxL+6PZNz4j,iv:LHvGgsi3I+kKZVRMbrVsIGonHMqZce0L3YmK0ld2J5w=,tag:0Pugh4imM65wfSINZJswrA==,type:str]
      allowed_domains: ENC[AES256_GCM,data:2MnahJ5x4VHld4d3,iv:lNSCIe/BHhr4qcD48Yy1PsdFu3HY1XmukqPtKajoCh8=,tag:wL3zKRVW5q3QlX58EIxTHw==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:61h48IjYCO82XQ4BMgGauB5q4fkFVUiYM08vJQ==,iv:iu4QgXKV2thHrcz1e/xtcPOjoQc8gJlJCi9cAyqR0Vc=,tag:3zm+sUZo9OoaqdLKX4sMHw==,type:str]
      hosted_domain: ENC[AES256_GCM,data:RewvFNtBnc14hoAL,iv:LeAB2MZg/uNd63Yb3GCoIKR+KiX8ahPNNs1hVRP2TjY=,tag:AVNuUUnQ3/GZCF569235rA==,type:str]
      use_pkce: ENC[AES256_GCM,data:KJk2Ug==,iv:6/JZjgA1klSSNdQCah572MB4slztP+/LjACq80q4TeQ=,tag:nhBWxRtk4xQTwhqdoDMFRA==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:Y2Wk8VtBiCukr48sP1KkcL29hmZqSg==,iv:HhhqMCygZktjFETLi+yON0jmhYlSx0rBFTokOuNMg+w=,tag:jqUj5dutIWgRcKHVruL7Ow==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:bpRrjW4S4blfVql9IJAZ6Up/k5JJ7A==,iv:G9/wlJn/Ax8ooh7CVSlyxV1UxB49aa5676DMeNbdopY=,tag:C45UJIItU0bCCpX8XtB5Kg==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQXFHUmdUSXE3K3hzVVdB
        aGcrejBRajlOZ1ZJaDQ2NzVSK3M1aXZCMXgwCnhZbFZPWDFOaFFRT1FTWkMydWIx
        VGpITlFKc3NwZkxGTGd5d2FWUVVYY3MKLS0tIE9ENUM1M081K3RweUNJdllxMklY
        NUFXajNtSFhycm5COUF0cmVGTW9ESDAKiQyEUeHuUrW7cD/w2gHKXE0ad7yeh629
        2GYfbJukzDritCw8LNVvSkhcEtNVCf0zthCx7ncRXG/BL2jIQ8wNtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-20T12:47:07Z"
  mac: ENC[AES256_GCM,data:FjYNNpkUQKn0WPBKJT7EfjBuMDgcQcVquxjWZ6ZAaxoHDBPBHzfmmCIGYL1bVpKjmmodgmsS7Iqa4FJVaMWJASY3GVqj+X6wjaCXpxwgI24cDj7hgoX8BlHUkOXzKyjkvg/LsJTdKRd4x0nqgD/3AwPbCMIS9PaAakstS1C8Tf0=,iv:nHXYssHlITuSoHIw+O9kPF4a9bXkYV9nyu6FqHFg94A=,tag:JjmaFHO25NOtFgRBBhP2Ww==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
