grafana:
  assertNoLeakedSecrets: false
  # sops:enc
  adminUser: ENC[AES256_GCM,data:B2/yET5JY3Sf3c6k,iv:1fho3xZHU8b7Dkt2nmsI/KlLgYDgerkPOKpGwtQ4ZII=,tag:suRHz4M7wzvp79awqz1upw==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:1hc3nw046cei70vds6yclKhF1uY/q1pfr/fr9LI8mmo=,iv:IcAR0RAslkbWisHQpbTqvSW6vgXI6ETks55QOjjWeUo=,tag:uu8X+9pcRZQUgQitR9jACw==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:7+ZSbTy1nxfF6tTl6VnDrqOrG9EPNw==,iv:WQ4GG7hqT51jNt8xCtQcavhKWdDBO6sXTpCjwjNNBdQ=,tag:vLpP/8RyOx7u0m3+7We9Pw==,type:str]
      root_url: https://%(domain)s
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:U7rKYA==,iv:9oZ0vT/rGsH6gG5iG05eZ68hQwPf4biDUXUkHYUoGqE=,tag:BIxfCz6mU0nSEJMO4h9EkQ==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:Fot9RQ==,iv:AAxsYIJKcDu8GWxeczNhGnliIvILnGWhyViSl98q/J4=,tag:EsxqAyRRCxHtQMAL+RgHeg==,type:bool]
      auto_login: ENC[AES256_GCM,data:mhi9gg==,iv:ArWcXyZJK4H3QHKNEJiBsGYv0USNyt5mLJaG42k6IPM=,tag:U2IDdbGnJrdo/vJ1R790Sg==,type:bool]
      client_id: ENC[AES256_GCM,data:BflauJMmRJz4pguyKnTq8XRI9/FUDpFY3t7lNfLx6kpxAPj84B/CQa00Z/fVyteJxbToLaBSWPziytmpJFasrj3vMNyQCDoY,iv:Nkevwas7Dre1tF605UqfE6Z1IU60zVXncKToO6gXgDM=,tag:WdST+ZTi344eU1z38Y07Vw==,type:str]
      client_secret: ENC[AES256_GCM,data:eG89dxi85cTssTSaXTI+rORrrmrxzentjnCWeVfK1i2tfpQ=,iv:LzGN7jBLRRqMY4MEFMjpyF9fprDUOdc1y++xYQbgR7k=,tag:y7Oo5UgT1ug3iTzK5b3Q9w==,type:str]
      scopes: ENC[AES256_GCM,data:FSPdMpkyw8cv2AEa9HI1nSxmYGjRgQYr57XVVy0oY7INnk2yvcH4OL5+gTNI5QVRJ6713WkqDI84gy8Aw3j8HVm/MfMtxypBLtrZETGNcKyRjm4=,iv:gCbsfOtvomozBEX55lH6hMCa+kkVltl+d8Xw8aFAejk=,tag:/o2sU42y3Vr308ZLPJ0qEQ==,type:str]
      auth_url: ENC[AES256_GCM,data:YEof2S++Uf6Du03YX0yn85VxO1V+VO+zDl6lJe9G4naDaMwVOZY5AXDsJwI=,iv:pDDsiuxKnMtprE3Z817EP6XUOAbE7MxYfREW0rk9WN0=,tag:sLlZfFijl5prV98lKOjLkg==,type:str]
      token_url: ENC[AES256_GCM,data:uHveCfRCHah+VjTvDgWpzqYwsFz5phkaSC5dGQ4iyIAwz9c=,iv:N0ah455tmY8+V23BQCw/zv4tSn7KZ10pIx/U25u9G9Y=,tag:CDPrEeEuWnTTug1QfdZ1tQ==,type:str]
      api_url: ENC[AES256_GCM,data:eqz8In6Q5OCvlSGIpHi8ZdffnAqMoMoL8nhrFgO+/gJtxAeNgUQYNXYOzgWVr4EK,iv:bhRo7jjS/HJnptNnxDpsgg4WWtSzXh0ni/rcR5XL/Wg=,tag:nvZNekUFKIZhOytj6NQM6w==,type:str]
      allowed_domains: ENC[AES256_GCM,data:xZjb9M+vhN11txqd,iv:SId3O/kobzGkMf3Jv2Icjr5m1coz4xjvZxfKS9uisxI=,tag:LSXV9EE6DQ7/+GqoeS/E3Q==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:tCy3W4ndDZ6dPUXN/w0vTJ/PaZpun4AHlK9E6A==,iv:Y1l2CApfCCMF7vRdeLd0AjDATFUX87cAplvVFkbDHHM=,tag:BinPpBs2dCtTzXHT64zRPQ==,type:str]
      hosted_domain: ENC[AES256_GCM,data:pdOJPZhs5893netQ,iv:Idt5q2FmHRXnj4Kq5S8pst46oCAoj6Ro6KtaJvTdBck=,tag:sWU24Soi/uWl+ULtlxwTAA==,type:str]
      use_pkce: ENC[AES256_GCM,data:SvfQ5Q==,iv:is0MxTDYCU/Uqjsf/w7AbUWv4VXakELkftP5PIP2EB8=,tag:s4exbJNGVm7Rn+dys7EK4A==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:Msxcgc6Fly8mQEg1wUsdlBippp//iA==,iv:DtcIBBVg2xTYwvOr79y2h++fqHlLKpEjMNpNAQfSqxI=,tag:fz4A32r107m+47zr9V0x9w==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:apjB0MkPnht5HLKdg/HM3wkNVS3dZw==,iv:BvU0Lkbbk4kNUuCK0ExJQ2P2RiEoEV+3KoOtRqHuer4=,tag:zEoXt4dmQQgNZ3PYjMYHfg==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL2FNYU1VY3RtL21JcXRk
        eHpDY1RWVys4a0svRm9YTVd4UThCRGdWajFjCmZGbVV0UFhUSklGOGNveTZYSzV6
        emdkU21XTHdlQm9qTk5KY0kvdHVGQkkKLS0tIElUYVgzNUd2MVV3OGlhMGJhcjlH
        Slk3RUVwY1pNY1cwZ3NCUlZGNTdVMkkKXYczlsmuQp0XwwkV4TC9Y614a7ByGr6i
        NPxcVaokPXc3mpbD9wgdw1VPHfqt3wmB3DMkleCo9Og966+Z0e7lZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-12T16:42:16Z"
  mac: ENC[AES256_GCM,data:l4AsT9n+oQB5ee3N3a3FhxHsjsxbk+xrzonII2hYgnNh/IE8s71HPKDajkt925dzVDtB1ELLK+pXwmfluYaxXjp3DtHMzkIG94kHfn4pWNoHBAkDcHd2Jz5AuzsvOMec87DVprE54YemoESnpFQ/LQfFBrevPhyYqPBWxVwAeyE=,iv:jy0yPHlcZwASe7QFFAp+Wp7krMncIBo1gsHo/25finY=,tag:8SXz+ZGCaUbcPyMTZA/nyg==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.3
