grafana:
  assertNoLeakedSecrets: false
  # sops:enc
  adminUser: ENC[AES256_GCM,data:qaWHbNWe69Mrwfto,iv:Iz2Sq5jWegy28Ok0+En1FFx7MQVs+Z2KD4jbHRnzSUU=,tag:tirALm2ihQIM4g1Gn/y+rQ==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:fzEZuIxp1gBDJfhDdqBZE9X0ks1dN+tZdjMGAxnF/z8=,iv:mF4TL/2mLrcc5lm5XKJMnEO0Ya8wU8sbetdRfuUqBt8=,tag:jjCIQNMHhYCbzRPwXRYdgw==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:YHZMyGb3UwoJH409HAeu1l+0uMHQtw==,iv:VgfRQuaWKh8sy/N3SKUzVsi5B2X57eQb8/mbpIfKtJM=,tag:PaP7JtTsQJ59LxgC8BiX2w==,type:str]
      root_url: '%(protocol)s://%(domain)s'
    # sops:enc
    auth.google:
      enabled: ENC[AES256_GCM,data:uNZAaA==,iv:t/4yNUDIk7Ki97nVZbOMYW2JGIy52xYenMgqmXStD1Y=,tag:edO6iioelycBA2OL5hCsog==,type:bool]
      allow_sign_up: ENC[AES256_GCM,data:zPVLxg==,iv:wj1xuuMnJmcEXXRboXhY5U3zjgvOwrtWcNFVtuvnpmE=,tag:8RTHWHmcjaXFI6XGlvXqWQ==,type:bool]
      auto_login: ENC[AES256_GCM,data:1MEF5gQ=,iv:+EEivsw7Aq6zXokkiHJpd4KN8mG+6Z5YBg5NX3D595w=,tag:LqVptBeG+ynIub2CSuf79g==,type:bool]
      client_id: ENC[AES256_GCM,data:+JcgHJ+neTsAC84W5sgqKBO62wneeveWqAkNbR/hxNei1o7qNhngQWgVmHpZlB1npOFyslRIwU5Bg2neQTe/6PWvlnyBX3Il,iv:c4iU2elQRRTG/AuGs/i35c9S9eYe/TMdbnMNrX5lOYU=,tag:p1tZwKkVMrPLbfBBoxScXA==,type:str]
      client_secret: ENC[AES256_GCM,data:IMTFHz8r5DeOja08H1LbcWeMAQDmlgiAcfLls5fSj67dojI=,iv:PWxmwQBDEb1TcvtnKSC0zWiDwiJFRJ0G6BKh6uFjS+A=,tag:x5bx8AjYFHvpSzB4dqR77A==,type:str]
      scopes: ENC[AES256_GCM,data:Bjl48RDDUUZ8QXA7opW+XzvMNPZrsnSsK54DHoiGpRkTKo/oujV2UUo4dNRbx9VOafkhEojO9ctsZfD03m8fiOFbbBqsiP4i8V8DnLJoVCEHTbI=,iv:zSpacNhYdczVgfJQ/xcQWLHMAsDs5ZJIGDRm3OlpjVw=,tag:acyqwgIvkWi+YFJs8Quw6Q==,type:str]
      auth_url: ENC[AES256_GCM,data:MtO1UZHbxeBmgz0jn90dnOzBGrMxHZ1obXuVkuFnQa8ceQg08dZYHl5I2fM=,iv:TMX71c+QG3cEZC8iWn7s+gBdiVO52qlB8EaKFgTlq/c=,tag:ZgVJXFjZl8xUZnYEQzMF0Q==,type:str]
      token_url: ENC[AES256_GCM,data:qcnXEhWppBcVQzKkQnWLlIqnOJXgj8mB9W1AIzecytN8HDY=,iv:ZgJw2qYEluqd3f0FPFyVHifWA3XLh5Tmc4RnSEAPfrQ=,tag:B4aF8/vba2DIeI9pvf8AXA==,type:str]
      api_url: ENC[AES256_GCM,data:Xnj0Sb2i+nSOuVY7CL/3dQqMnDmt/8B9i17uWlTsxbZIqQ6f38fE8tAuzXgAns2b,iv:TK/EEzyn/7QjdOPhFkGlQBtDMks79NtrMSzj6ovPhc0=,tag:Lrt4FZJDNeQC7aEKoBKExw==,type:str]
      allowed_domains: ENC[AES256_GCM,data:arUJpteuKB5yeFkN,iv:4BCSy4pVrHDNsgMnVZS4UfX0oMhkmgkuj3C6oQ31Di0=,tag:RlUUrlHGfG3dBSMvvzDXhw==,type:str]
      allowed_groups:
        - ENC[AES256_GCM,data:m7B4xJKRnk1agpXiKqiwus4Fk+ftq7T9WW0GfA==,iv:r+BULQZqFFKJVOm07HW1D7oz0793uWwyAUBNEOcE/mM=,tag:VlqeT79QUiFPVs1Gv86Gzg==,type:str]
      hosted_domain: ENC[AES256_GCM,data:o0jFyCYBBWxD1pxy,iv:ltNZKbT+rBOzOlwK4UA0oATfddbA5jSHg5hd8xJsjaI=,tag:5mxtAAohTXO/tCzAOU0qNA==,type:str]
      use_pkce: ENC[AES256_GCM,data:9jwD3Q==,iv:L5klNRxu6abbmk0SXm4WsMzYytLZOr2h1E2SaWs6T2w=,tag:AI6Ki3VaGiw+0FLTZQ8eUQ==,type:bool]
    users:
      auto_assign_org_role: Admin
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:PyZHVLOIz3UxoejuLXS8l7eg/OsBUQ==,iv:SFFQq7eiGgEHitpkBL7Rj9YgutWoDVvS/0HPhStcaxw=,tag:VltHaLiJs1hMsD5JsOzwxA==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:XF3sqwMVwTzwqT1+VZNiGly2mBxPjQ==,iv:gdsyrjLsWrZf0SJKC6aJ4GjHYbx1kkgobf+kvzJ75o4=,tag:NllDRDAuegH0z8l+NS9aLw==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeG5rK3gxWDVpVDg1ejJw
        cCt3Z3o5N2JNOEc1Tjg5d21oeWQxMnFPVFNzCkw4WkpnbEYrNFcxY0x3SVVzMDN1
        WTFKZnNTTG1qQ3dKOWNMelZGRnNzMHMKLS0tIEI2czVEVEVsek5OWjV6citZazRE
        TkF3UGJOMDNMakJpU3dFdE5pTnZ3d0EKE3VO8EdM6u13Un0y7DhZZsRiXBjZMhK9
        SRhwSduVoUVCKLAtAquOlJ2ZzZ1kDBiRPpMCAJcz0n8Jwx3ZFwa2nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-20T12:35:11Z"
  mac: ENC[AES256_GCM,data:WZ6Qnr6GpQmu47yKgSRpg+Sm0gdMYtqSxe3LzeVWwtpklJ9CHjyCiu72Cw5UpLRjTxFQG7RpNkvmeCfp7kO0lwY8PStQT69djBzt7/nEhItk17d88xPmu+WHqq57O/VF+7tdpAONcxX365cQaWOdv5Xk5SEctHNLYX95U2i3XUM=,iv:xledqYQRFde6gtdnOcv+5OabF7gZ2npSInu60PSgoXM=,tag:9TElQlQ7clrRkiaci3+7Pg==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
