grafana:
  # sops:enc
  adminUser: ENC[AES256_GCM,data:as262G3cXPzBhOlg,iv:Hct8a+8uRkRfMqf3xveY0RtigCUh6wF/GjKcQ5Ir1gs=,tag:BBOt8JZ6GGjcaXYtwFDw9g==,type:str]
  # sops:enc
  adminPassword: ENC[AES256_GCM,data:mGHMiQEIVA5f/dccKKf3pOlsijzWQJmMjHQq7p2ytiM=,iv:lO8GehXmfHpsNmDPHpPC8FHS7RPs0Kr7QjLFmavVrWA=,tag:ksbPFnmJ5WafD/WDWTpTLQ==,type:str]
  grafana.ini:
    server:
      # sops:enc
      domain: ENC[AES256_GCM,data:YPRNj4/+xg4CdG3QZYiYH0PR+hVEOw==,iv:AVJCjylYXlhVWGDrFf+58/TFT+rBdygEWRde24HVSOE=,tag:ox90nIpwzJikq7KxEMcRbw==,type:str]
      root_url: '%(protocol)s://%(domain)s'
  plugins:
    - grafana-clock-panel
    - grafana-polystat-panel
    - digrich-bubblechart-panel
    - marcusolsson-hourly-heatmap-panel
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      haproxy.org/forwarded-for: "true"
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:bji28jPIhcw9R7U+tjMx36r7/L6J/w==,iv:2+W6enKSGwE9t0HjGnFQHB30MEnpLyTXXYc8iSJSqzA=,tag:b0cT7D4kJLDh2LDqMitTfw==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:xsaycwfeE9+D5pn5qNneUDZNSJef0g==,iv:LfWlEoc0D/h7QR8WLwOMeHP8O7sbRtzXjPZ0FOiKhOI=,tag:aXlRZsNFfNisghz3fEIjqw==,type:str]
        secretName: grafana-cert
  # https://github.com/dotdc/grafana-dashboards-kubernetes/tree/master?tab=readme-ov-file#install-with-argocd
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: grafana-dashboards-kubernetes
          orgId: 1
          folder: Kubernetes
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa1pISTFlb0l2ZFVRdWF5
        WHA3YzVlWTVhOUZMQ2trcnNSNWt2YU8rTlFNCkVESTNFOEc2N1FTTElHVmg5ZXNO
        RVlRalBvdUt3YTFxR3dxSXZuSW51ZWcKLS0tICs5K1ZSeHA0ZEFGTUtSTDQwMVBz
        ZmNpaUVOSzdBY09UV1FjUjhIVFBZSkUKgMRoTFx2GELWmlRLyfqzu7CDPl+v1jdp
        vLQ+RX7QgPzsLpydDNI9xz9BjomGd0+23JBCkPAMFj9c0SomxEg3pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-09T22:39:14Z"
  mac: ENC[AES256_GCM,data:Knt2QvqW5ZSpv4ZgFpG/gXpyw/mvYkUJ0M2/tOKsB4t7LG1qo54+udbTuFB7F3usuQeRukZ6/ivEiSWi5zlLcOUIdKFaMKJf1Ydro3c4Z0zoSwXTfY8Xon2UhqVylE+Oe1Qn7mvtuF3ZMyBeUcnCZCXzE1PhFPGG7okYpjjTKmQ=,iv:ji5Y5878EdmbP4CF56+U8Q4B4JB1j5/CSk65eT7KuuY=,tag:sEj3odXkwNfZParlJyBpaw==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.0
