grafana:
    # sops:enc
    adminUser: ENC[AES256_GCM,data:6Fdr6GaODbr69E99,iv:DouzVtkuOycgT82bEO/fKBFGwa+mOyfp/nL5NNfyvCU=,tag:aLfamcL2SsfD6fyFacqxLw==,type:str]
    # sops:enc
    adminPassword: ENC[AES256_GCM,data:szS5MCkSdrqoHW6VUxABfzJoLw5+zUXl0yPReuWG6gk=,iv:kpgQxRnOMwoIfpjBcC2KccxxOdqHu3yNhdVDdLmEv/4=,tag:OC5upQS5pgZyM4/m3RuMUQ==,type:str]
    grafana.ini:
        server:
            # sops:enc
            domain: ENC[AES256_GCM,data:U4ASjlsjVSw98sdIndfEy48czB1ORQ==,iv:ynW1B4nlQxkT477nelHBgzmzAr/p5Z1tqABzo2+2Nyk=,tag:M042MbRF62kwr00hw82UBg==,type:str]
            root_url: '%(protocol)s://%(domain)s'
    plugins:
        - grafana-clock-panel
        - grafana-polystat-panel
        - digrich-bubblechart-panel
        - marcusolsson-hourly-heatmap-panel
    persistence:
        enabled: true
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            haproxy.org/forwarded-for: "true"
        hosts:
            # sops:enc
            - ENC[AES256_GCM,data:mnYOkrRw7DjdoSgY3FILKc4+/VOBEA==,iv:AfgUEOQApzfoxGhdoUxTaJjNo59Khb1M1bRd+xu71XM=,tag:V3MacsB7m5/2E4Adrv15Wg==,type:str]
        tls:
            - hosts:
                # sops:enc
                - ENC[AES256_GCM,data:wuimsxrKprq+lrMC9tJ3B7gMdkWp8g==,iv:JRhY1b3uWk0b1XaOAliBJF6FC54lY/J+6rYhiCwEjQo=,tag:qnmFI1aRwF8UOR+kSJw0Kg==,type:str]
              secretName: grafana-cert
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL3pyRHlXRU1tb3liekJj
            RVJhbVcweUd6MzlMcEMxbzRlYXg3dS9KaFY0ClRtTlJSL0xxVitKTkRpRTBIWWFw
            UlRhd0E4N3BFWXBlcUZRVW5pb3BYUlEKLS0tIGxWeUozRGFYNlVEVVVTYitLZkFF
            M1ZnZDRrZVRDMmk4ZjdlZ0oyMkI4MkEKGZR/CfNfHlsnVWD53B9VF1uxV1DpLQAE
            XGiNQ3V3I6l99nT5TTAnhQWKTfeAFZJVIKv+ASsyxvl88exLPBS4QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T08:07:31Z"
    mac: ENC[AES256_GCM,data:QrSvz9MMkF9LkLOZzqRm0UtuAYFky5FJ11tufWPiZwBcP6KVfqdGFIYe8oAj8W33jUECqnL9yATJtGK4oDF+hmm5MSBjtiBx8z8DNpff2Tv6ZmDBWsLUCcxzWbBOWDk6vWO8DjtwlKES1kFgUJ4Z5pPZ5gRPSvCOIES3Y2OqCL0=,iv:UP2MO+A3P+dz2fgSOjSICdUxvDVl9YzV1MJeyoT6ITM=,tag:QHps3Q9rb8Z84S7CXOuQLA==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
