# sops:enc
cloudflare_api_token: ENC[AES256_GCM,data:pTQzigbVyvrWYsH0zUcrWE5kejDJWrlUfCjj0j4hfgzzD1BIQkibEg==,iv:bTum+j9dUN2m/6SRcQqv8OfgB/L+TtMCgMVPhY4Bapk=,tag:TYTaJ2b98qrgAoil54pHJw==,type:str]
# sops:enc
cluster_issuer_email: ENC[AES256_GCM,data:S+hRKlKDMEvlbD/0YK2VjkxmdUaeGwlUyw==,iv:aBLIsvTRs0hk3gF3qlo2tHPdy+2BzjnJCu0JT/fhOi4=,tag:Jnkl+g3uh87flvkRXpTygw==,type:str]
cert-manager:
  crds:
    enabled: true
  prometheus:
    servicemonitor:
      enabled: true
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbDkrNXJYNEs1c2hWb1Jw
        QzZCT0t5M3BPMWFJbDZnM0NPUUVGQjQ3MERZClpRcDNLcEcrY0MyVDd5WklqL1Z5
        Smp4dFQxeHlRUkdWY1F4M1JNRWRNQ1kKLS0tIG5scDZmVnNFYTEzLzNyVDVCN1c5
        QkdGQkE5NHVubnFiUXhYY21DODk2RUkKW2HzUuOE0eva22hIFfkvR+xuR+i/vWzQ
        OqfZOwN7P7tGi7KtzuobLtL7uYIak2BRwM+iJpX0Ur7vrxeJ8rxhVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-09T22:39:13Z"
  mac: ENC[AES256_GCM,data:3WHXTw/cZuVwLVheLgl9Dia9058u8R6rSHNHovO4q7Tv0GYafh+MfmJN309SXTi1cAhk/SKW/y0tsDVJj9UZEeqY/Cv2oG9+ck+DFOBomsG1WWfNiaBiWWG86B2nq67/057A/LR1yhNdLGEnxWR5nh360Guz901zza38i7qaxuY=,iv:95KHiMwtD5l4nvi9pVjEihr5zliKgPJ+9GCy/RuzOpg=,tag:JeLEO7yrGE0X0n2/yb05jw==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.0
