# sops:enc
terrakube:
  #ENC[AES256_GCM,data:LibaVtngSNIxGmVhGEj67AfLJE8=,iv:KEPRu12rKXgI5mjdXMFnYp1IY6dVdXEi1hGfEHDKUks=,tag:gueyo1tVQxfPXgIW5t+j9w==,type:comment]
  security:
    useOpenLDAP: ENC[AES256_GCM,data:TER766o=,iv:AaKhzi7/R8W3FOYmEN6/E8lBol5Kthn57q/Ku6KVlFA=,tag:zDP364VR2LzcSzEAjvmsJA==,type:bool]
    #ENC[AES256_GCM,data:cmxTTPGVggBTW5Zw9t1pfcVfDfkZ0owyunQiW+zF4WVaHYhnnghkMiNQGLeTsyrPCqbtPFWdlIrUUbYD2MC7GcKEp9G0rlvwpFfOeLWJp5dpYMPb4Hjx0pGnLmbmdKw4kZozRPoRNOX07aw=,iv:X+EGfgoRMXVPdxEsGPWTHfU9PB3N2WMXtMZ61+oFW+w=,tag:Bo49CW3c/veMtuvTtAmYIA==,type:comment]
    adminGroup: ENC[AES256_GCM,data:4vCYbmVkBIHIqvxcIcqXEHQ8GmVcG0VSG5sBTQ==,iv:JI94jFQKegW/5QwsF8XH0E8u0AXcHnC1BpvNXwREhUM=,tag:VUsYa6+G/sh/f6Be24Pjjg==,type:str]
    #ENC[AES256_GCM,data:xA2oGkj/CMELoe9RFKmuDGc24KDkm3pDY8HAoujJuNcWE9HdmWY9PDFQXgTP8igUVLoVAwz8WRcjUQ==,iv:tnLxhBGFyKGqKbM0kFjGCWcdBJu2FS4ckT9od9yhaVs=,tag:SojNiu0rD987BdVaxiWN7Q==,type:comment]
    patSecret: ENC[AES256_GCM,data:61MA0Ui9cj9lb8d+d6ceOxftIxUWCoIeP+u17a+PEhI=,iv:PtM4Km0tRhKlL8chJa66zV+Nf2/jwTz5KQUBk0jE2bs=,tag:GezcMiditpBiPmPAYbbUzg==,type:str]
    #ENC[AES256_GCM,data:ESfDel1+adnAdeGqlmSLGCkd/PNdk3XVketG8sLAKlMQDU4OFi4vXajq0c1VrGC1F4CeR4VNHwnzwQ==,iv:Ol7GCQoobd1CeLNWq4umX0gC1kF814e1bezSkNvfDqY=,tag:wCtclQcvvWevorKzA/nFCg==,type:comment]
    internalSecret: ENC[AES256_GCM,data:diT9z6x1YCh9tEcjlim3B0w/Bn2piKggSKZ+w8BxBvc=,iv:I+usClK6OHcPPfxD5n2so3ylb0ebGmH2RlqigwfyOIg=,tag:8wyyPUI4koFgENSeqJ3l0g==,type:str]
    dexClientId: ENC[AES256_GCM,data:JEchecuc,iv:9EGxY0eSFRlF0Xowuvy9kPwsU6/xyDoajW/2d4aTnL0=,tag:Oi2U1JH4+5Z7iSrLY84J1w==,type:str]
    dexClientScope: ENC[AES256_GCM,data:FtHTkcCIxblfQm72TMQJituzE52XSitIDX1qvW3FR396hRoJFPrL+j2k,iv:vJ/tDGILS5rdV+OPKLnbh+u90svD+/K1cUrHpF7EtyI=,tag:tQqvaflajoIXnoSk2Qb3/A==,type:str]
    gcpCredentials: ENC[AES256_GCM,data:VZn2CMQd1g7dqROBLyOdEMwmMJ0lKR5CsZyxTEg/Sr9GF9xiGChLNOu7QbrpWToqNelzTfUlNlcGIaeaCHlduNFbJcF80CUV6ZTN8NxyiGhExCSq+wqkk8/BE8hZ6GIvnpAJBcao7D65ZrajTVflc9bytJoQemILzABIIwGD9Fii+5iPG4atvcY477Owbg470DVueb0Q7IsAbWrXXV2uFtbU4hh30NiagQoMfCioC65algKKpUt1nZO4i5yOZrb12PK6INV/w/y+vB0bnageNS7UZA+xET2+ba6ZRGV+E+hCoaCHjEBMP7KzZZsGstEa6o2EMZLB+ErHb7f6jeJp9I2MOC+91EGs4jejyltwt9LhU3Igq4l3DfqgMMAX9U16pGI4lPeJNuKUJstgCjsAcEYdqPx5Fnfa3Jhj2kynWfvUnVOEbvzFA4ghUplYCbxHqY8fvvHFbmW0zUjft8L9P1H5IA5paX3NHd5AgDi/loVLzfDny33uTL8CivCFN+jwtxbvmW4z6uYptEm7pxx5wkIWX6qBOFKhaC5MRDGNaNeW7pE8AYfohgddcFtV94ZdpxD1z26R9L7hPADOvdToVJP1hAdKXpylTcN02Q1YU+kLHxvFA8YYd7Audoy4zs0vO/5V7l1xXpMdisRrGOXoMx6vRY5j1SUZZN7qoa/j/Qslv2tJ1EotOFl8wn9Wd+vDn8SP22B4NEWKS2JrsTFJEKSpTWkhdpiIz9dkYTumCbJGPtm8ewLmpcQ3BgerVs0E61c2s/6vRA2/6FsOZF/8+C2GecqDgRPWt35nmK3noo6s8jm+GY1P+4i3wX/VP5KY1GhIXticDjPJ3E7rmLB5EN0G4FeraMvt0TLGPXIcDjWaBoHc0UKlNkvuGQqIKXAvpA6tyJMy8jA9WUA9TCpE7pm4GA6Kmcl3f9a2EYjpHj9P4VlDAKSTCvbVyFESeC+/v2NaAczgSYgwvFFcuuulTp1S5qR0YvKoTjDdXGEuJWNwFPSRxiIxfg6ddT8QxnSeV9LZ7C74o/taHdtWAy1k1uHG7Qs/fbX6yDqke36RtaEVKWC3KppAJYoGvWvd4RowG1xUxQJnMR+If0QLG08rYTvLGeh6wSIEGkMKDTZAsMtUSomDTN7Nm9oKz1lKC+R1oMBYeLURn4gOcw26E8mVkgbmuZ2tXyY9KT/teyb88q65kZuYb8CpSzEuGlNlRXRXq86Cc5NDYI0r+xl9xF0wS5AN6GnhRrhCGasq8HdCFFzKnHnfZ6x/fYsxxuVW9xFUT2ZbvK8HAgJYeaNu9ChrEuwQvaBKjdZavAO3dyKw+nqe1r91UySIqfJCB8dKNS/dskTjTf5i/zb84wzXxzj76Db/OLDw1bgjvP5JuafySPv9A2b1u/gOrQq2yU3BXTMM+08emkNIuJIa0tBqOFIXQ0h+6tDHMy/Ho6x0NC6xVdL2BIrHhP9nLizdH56jUgABKSIYwj4H9kq25XJLstNkjWToGDwtZqp3sa1Ek29u5um08Y0D1qspaFPsehxYGU4MKZ/0f5v+Jdus/9L4ikzUHE7lvyVVm6+2nwPxlKyEOiCFgCq4zvl7fh2r9CMmXWPTcNAjalfSES9Fk4ajsasnaYh1IrVKTW66Zz6vzFjBDzSs2RzcTqNmsFrn5NLgzOX/37Rshuacf7m3FlTsfLcc2isZFEMNXyKmyyA/vFc1vOvQ9lCy/S7d05xXZuI8c7ohhIIkZpognlEvrX0Cli5MEt1Ud5f+u+aKQHVnMJoo1IEEJshYLZUMLjb0z2r2MeMjW0k5TDKNCZydp6KEOoIQgSAMMmIGLWb/VDmhClGpD/9DsIOSkwvE/y5/cV61vhewwAcM4+sdqWc5mVSuebW3KLk+eAgendo7EQOr2bz5vGHlcgNXuxZbAimIR0qK8vG4uOmMewRqkl49GfVdBETF5qkt2NsTHDj/zVhAXr6oLFtkcJsJ9CA7PeeNLEPB7dSx1iBckhU+7qGpejR285uhwJBqZMX2GknhoiVrPG3zunVZfd+7uOOuVvkrBMjs9YThPGTJgXDICwGfIUfaqxQxPm8sLj4gc6pjUpot/koPhS1SIrtqvQOeCVLwLto0pa9aAexbaHdiCp19fOwEtCok2QAJwmI2NSIWE1c4ZW5iUcrOykadAcpb7vMdALMdB5j6cNqeVC8TejI0iuRe1OZd/DGunvXwkN+l1vxvxNbVT3NqX71xfitJ0iKmtCOOQSkfpd+2oULA855uKzoVzgykz2aE7BLv/iJ/LdjYjDPFPSGqu3EHEAHatXUV2Bod1B7Ti1mR/UpEOa93J3brxQ05OVXYS64693AA00ZeRCI0VmQJiWmzGLV5W+VRGif4xYm3VB9/3NL/Y7DulRcfhbQqylK7t1Te5XIUAsNptW9p9DcHnom0UDel5iETtw3++bkzXesPhg1KBz9qce7DD3JCwJWMJsurjO4aUYNYENPqKdpDHGWhLE7NxAOTXtTXlmzYOlBkLqD1d+skpgC5020a0k61Ans2CmUwrUMlsafSGFhGRPzHszduVQgxZXtyLT6TvhN/mWnqIlJHEZaop3mFhWa1Q5lft8TJYgBFr6s16i6NHpWFGn5q/MJ5p78V61ZO4L89UDwn+FJkqa/3FMJhCEd/5RXMT8/aRWc7T96YDTL2EZaKVur99GSaMlyv4qJWyiV9rI2vrKXDLW4HqnyZ1EeQVn/Kko/tWu77ttTVCaLnO2DGi9UR6Uh6UTRh94TpI8v7W8IepzKlVPPlMFMkB559IvJCqr7H42Y16db1Oud0WObPUJltvHonhSfTOEsSK3qYsyiPU9r6Sr2+Z83K10D4EZNFiLZsMDqjnTz8J4gPS74DuxxqC6tIEjbcLjT7XOurZVcJhE0LU9RldJpWqBBx4W7D94EbDyBv0z82czZfiYAghCpsrZP0Tn76HT8aFidLQPtzr9iWTQ37EZQMeHyyMqDVSlAFc4HJ1AF2F9YyjZn5o/HhPnHTXwGynMNK2z3EirUlqAn6XF2L5nAx91cE3ioltUtDcPaZahJ0/PD8G4/iCrPZnDKyLj1vk+rHLarcyCOdBxXXtUW/R7wnfb5/cX3ZQm+6e4/zK2mRD6zkj0x2AE3IeMPfXFMhtFGOzvRCIpM6w1AR2MrELcrt/20MQ/aHmOl63updbfyTSQ==,iv:lkQlXzK3ajXA60PkmoA/5Glh4hjNmUbXDmTrHCV2Lm0=,tag:KBlcUxsf1t0o768/ecuLZw==,type:str]
  api:
    defaultDatabase: ENC[AES256_GCM,data:hE3R1AA=,iv:1i7sfhlf2NOP5cW0IoJXBlWRUCcoWfHFj0Uq6Zf3foI=,tag:THFv56zmOO2HOSCp9RZYDA==,type:bool]
    defaultRedis: ENC[AES256_GCM,data:GSlO/VY=,iv:tkjySV23jFHzCDlm82YlKM4S//rC0NWXaR9n/vMCjQg=,tag:JH6lQV4YkHAox1X0D2YzCQ==,type:bool]
    properties:
      databaseType: ENC[AES256_GCM,data:VJw0OAX8jKbvAQ==,iv:P5EDwjq4bwMHfjlHBzvng9G1/2X2As4lSoAFFwbSG10=,tag:JtneFg2wecsxiEOlNAf8rA==,type:str]
      databaseHostname: ENC[AES256_GCM,data:h/JT7vHO2QkRH8lOeemLeOvk+Ys=,iv:S9W3sZqUpR0BVMhPgALNyDIOFOxFGS1tze+3tICTPGQ=,tag:M9y0Api+XzgPr0naoiyAMw==,type:str]
      databaseName: ENC[AES256_GCM,data:5k8+i9mLkhNi,iv:7z7ODj5URQN0eszug1roGxiwsTZLMdrJJ/SItD0+pvs=,tag:HBd5m4tYd23tZvqC8yUleQ==,type:str]
      databaseUser: ENC[AES256_GCM,data:o38Som0VL67K,iv:T15XFaKY3UgJujNnMUYH7M5JCUAPzpQFJ6l47e9yLJY=,tag:d+7c/1VJ6m835PCEqGVrMw==,type:str]
      databaseSchema: ENC[AES256_GCM,data:NCxijFDH,iv:kKXTFQzqJSal7B6uPT7jOrhPwHxou1Z35kwKVlHFdSo=,tag:+HlH23dsPEvQsC1u+janIw==,type:str]
      #ENC[AES256_GCM,data:j0Eu+1LB0iR4,iv:bBS+nS6pJHvH4nLc2Jnw8X8spXMa2aTcSyuZgptXecw=,tag:63jNvLhCP+18todsHuWDig==,type:comment]
      databasePassword: ENC[AES256_GCM,data:4YaHdoEDlliVdeQNLYRgf0GcV2NUgnWrt8gTS9d427S0DHTTSmANfp+fJ70XcZakZQybQJOeT0TflvNr7jf8WQ==,iv:rA7at+rHAeF80jzrzH5+gJtepDIIsJjMUvbE1nNKmHE=,tag:jUKLnAKFwun4ksOSCnRQog==,type:str]
      databaseSslMode: ENC[AES256_GCM,data:YIV3CM1Nog==,iv:ytSdcRNcqt1cMmJNIwEcLBbmCldqgN3qlE1pxmgQWJw=,tag:Xq8Xm5qZv+KOzB7LCbfrHg==,type:str]
      databasePort: ENC[AES256_GCM,data:5X/0Rg==,iv:qnjP6bg2vZ2UUyZHNqVKsJipG0bJ5OxP5MgYFc3PGg8=,tag:2UNO/a5mUiW0BZ5iCwkfEw==,type:str]
      redisHostname: ENC[AES256_GCM,data:pSUNznOX9x+xeCsil3yHet9wT7KUTA==,iv:1HePCVug65xss6bUFm2+W9g75o40tBIunaW7CCSHiEI=,tag:4eC4OiqKs2AVEF7JwpziaQ==,type:str]
      redisPort: ENC[AES256_GCM,data:6YpkfA==,iv:IozajmqQncaVm7uGhZIBhIASWtefOQAVV3CHVy0nnbk=,tag:yEco9M4ZDigSdzhKJAYEGQ==,type:str]
  storage:
    defaultStorage: ENC[AES256_GCM,data:cdmDiXs=,iv:4Z4Mt5TMCZul1UhY3uJU6Jtai5vcbNhF8mLVqq5xgPA=,tag:SuvSq0P0o8xVDJNWhVCXiA==,type:bool]
    minio:
      accessKey: ENC[AES256_GCM,data:PeoCwxUmvAlYXYzBTrvQJyP2i7OfWZFeBQ==,iv:1ldqMFETg1FOebqRG4mB2hKKfqvsi1b6+ELmcMHWZNM=,tag:XaD34jD2zSOORCIXCYt8oA==,type:str]
      secretKey: ENC[AES256_GCM,data:FMoIjx+w4nNDcejsPaJ7/FdnSsQN6Gkllfy5uclrog==,iv:pFqcq0sBkkNT8kwEMODAYHAuGi4Muq26Uvbu19yKKF0=,tag:+WpAjlmosnGE4BkKBYA5dg==,type:str]
      bucketName: ENC[AES256_GCM,data:p2bMLpN9PKqr,iv:QRE1cSdWQcBIZGeECUKceEJeu4TnwKwhPYVrDr9qXZc=,tag:NLAdHqCm2OsWMmixmfngCw==,type:str]
      endpoint: ENC[AES256_GCM,data:DVHAE+1DQp7dD+xOzEe5TuZNG9A0VMdEg3jv6zKUhsqoOM49SehszWo=,iv:jiAhTSeCm/AAj6SVbwqYNr0YD0qFlR2MySKMae6HKrg=,tag:deTEF1zJdgPLJ6kvB2bWmw==,type:str]
  dex:
    enabled: ENC[AES256_GCM,data:n58oSA==,iv:oUXSffkv0wM34xr0KRkRJC8qOy0YWozcmBYvppkw/Ag=,tag:IZy6v7qV4Vou5VpQdypUzQ==,type:bool]
    volumeMounts:
      - mountPath: ENC[AES256_GCM,data:/gfm6+NVk7qFNhtlgIGY158/jiuWyfyGU1G0Itq8/w==,iv:kij2qBNfjQu2ROfrbyh0frOcEqpRCnMaseqyhlXRzeo=,tag:sVnPnc0U39DVo/Kgbv7mKw==,type:str]
        name: ENC[AES256_GCM,data:h0nxV7LXioclZA05ikgd,iv:UghRzCCc2Ysrgr6cayJEgwmRovDXJzM9tc3ISVTw8hs=,tag:B+NsU58Gv9B4w25lwmS+vg==,type:str]
        subPath: ENC[AES256_GCM,data:KJTL82Kvm/qCtuVbGU9b,iv:vKxOWLBK3mdu4qHl96XNNLddhwWyF5O5tY5o5XmFBgo=,tag:pCiY4rt+j0V2Y5VnK4qaPg==,type:str]
    config:
      #ENC[AES256_GCM,data:gjKnjOvG05ztAvKOLjYX,iv:ku81sL8wEJmnQTX8evhRvf3FuyQSx4wisVcSwl80wDQ=,tag:HfvcA2CJZl9QrS4xaPhrAA==,type:comment]
      issuer: ENC[AES256_GCM,data:6lg0aQhM89AiBePG1cO14QFtbTXvQ0UyCX9jeAd4xR8xwWuh0L4=,iv:UL1cGyOmxX9WAyG7jZCx7dA+ds8f6eZZMvEqA+jqaRA=,tag:O3py6P3uYMiRz2wtH75v4g==,type:str]
      storage:
        type: ENC[AES256_GCM,data:D3XsXBbs,iv:XLy9UwPG3FOLVBxovlSqUkV0kIGcfZvpVR/DK5zskNk=,tag:NuKjl9IlgI1UePpzSNlWRA==,type:str]
      oauth2:
        responseTypes:
          - ENC[AES256_GCM,data:fJgneQ==,iv:qxABcHFy6JvJXqtvsWfFnTMqQC9qXH0J+NkCVoqpdJU=,tag:RdR8iBGsxFplpNO+D3fegA==,type:str]
          - ENC[AES256_GCM,data:dc87lBQ=,iv:Bo/25LwSvj4cOOqbkh2m9D5HKgg4H8UKsSEH758dpyA=,tag:Ccme0MtApYSr3QTsdw97ew==,type:str]
          - ENC[AES256_GCM,data:SUsjfVcukG0=,iv:GzKBbx1c61QWi+ABPybMHbQmLF2FMR7d2C0xN8A9uDo=,tag:0wCJLkgxvX0BNpsq4Y3Y4w==,type:str]
      web:
        allowedOrigins:
          - ENC[AES256_GCM,data:oQ==,iv:mMqJ68RCN5iNbG690LaljADgkNEW1MgAh3649iKynfc=,tag:AkB9/5lpiyN7mG7IYZEHYA==,type:str]
      staticClients:
        - id: ENC[AES256_GCM,data:6X3mvJ48,iv:cm0rBQg78D6DjvEPuu7yCWprd44mXjhLjc7y49ClOc0=,tag:1MzmkO8Aryr92ur4+/g5zw==,type:str]
          redirectURIs:
            - ENC[AES256_GCM,data:Qqxujw3QAXm9o9FSKq73,iv:TYIQPVmq6wHxW8PJNyYYtIKpnUP1DBz4YK7ukLLpLZU=,tag:WrsElhvojzU8qN6R8cMjkA==,type:comment]
            - ENC[AES256_GCM,data:vTKYz0Fi1tQ3+Ct58034IidPlRfxuAwSzOtA9KbKX+QK,iv:amnGYdpTltSwNoJPUWOud0wimoMh9Dy5n70HTG3KRPA=,tag:JqJVIX4YBeFdu9k0mid7mw==,type:str]
            - ENC[AES256_GCM,data:nvbBAY/hYmWwx37FPHQUYxqmCKEX,iv:G1SN6cnLvpiI62TQip4rHEdpSc77VyK2bC1+r+7Gojg=,tag:cdX74/tYDsrGtkUC9BZl/A==,type:str]
            - ENC[AES256_GCM,data:zFtmlEd7TR7ePcbSaopBQ4i5N4DVW97wm2LjJQ==,iv:KfwMAd+bVDacpPKC2A0NbRmMFSRkUR7Fj8cajHGytlo=,tag:OnbEadRSuOMUwnkQz3fmcA==,type:str]
            - ENC[AES256_GCM,data:y56t/crWs/ivvFx6SKTXP4srkuSr3sjagyqppQ==,iv:gYsOVfba0s001tlm1VpkiOIYE2dn3t+VeRUVSx+wZvE=,tag:xZT21t9e0F23im0LTaOlEQ==,type:str]
            - ENC[AES256_GCM,data:Diq33Lx5JpJObkDcX9dqTQ==,iv:EoDaj27Jkv8+LJpTRazHp/lHt5gcqdvVUAPOR1GKDdk=,tag:Wh2BhMUozbEVa4FVg40pXQ==,type:str]
          name: ENC[AES256_GCM,data:4fuS1d6Q,iv:5b/aE7eX1H06fK1bIJpITyoF+btp7VO0qO8LjIuqQTk=,tag:RNiKj9ThCZIenVM+M8pddQ==,type:str]
          public: ENC[AES256_GCM,data:PwZngw==,iv:/hF3vLLTfQ/Cpp2W7XE1zsEor7tuUZNFZv295cwSlZI=,tag:8DtDHXAIL5VjzgJDaC0/jA==,type:bool]
      connectors:
        - type: ENC[AES256_GCM,data:8siQuRdS,iv:LFZHCKkyvmWkuaf05AMcI25JbeRqS72HxU7OcqxdIoA=,tag:QNJv9hovcbNiQUHvwMMPWw==,type:str]
          id: ENC[AES256_GCM,data:aB94oGro,iv:G1RFHG7TTmyMIEWmTnTUD2PEgreJtSgtQXUsmW9h7Xs=,tag:IoVz93egXyI0U1n6HkB0OA==,type:str]
          name: ENC[AES256_GCM,data:dS7f+s1Q,iv:1GBMKPbHVPzTRAo3foHG6ubNb5oVFGfcGIGrfmHwjqk=,tag:/l9sgwb4Mypnv8wxN+1uTw==,type:str]
          config:
            clientID: ENC[AES256_GCM,data:7RP83uPMf/u1bpkO9hXEE/rNkhAF8GAf3w+0PpxhNmVooBIhytRInT5PFNGPWfmYWxSGf2Pe0UxD/Ei2oHItzwdSxgxnzvur,iv:btzvk/btzGhd56b6yNYIqDjIgJAGOVMF54WvrmC3pbU=,tag:7UnHwC6PG3wyjJfH/eNf/w==,type:str]
            clientSecret: ENC[AES256_GCM,data:KGXwk7OdtXrNMWZ2BbpFUsZz4/V9vp0gvtpy20FdWynVvqM=,iv:V1vHsfyz+UboIN7VPVQkmI2sSs36U19Wo/TbcLQPTnE=,tag:NR7fKcrgQBIwKqM2UN6SEA==,type:str]
            redirectURI: ENC[AES256_GCM,data:Ugznt7B6DQkKXBl0D+xg72XPaBuXYQvmqT3mJ4nTmuo/H/5u5mxZckKZOdGIMyY=,iv:XdZAchMNwcULDh+aLeBNyf3MoF/uM2EaSqIIp92N4P8=,tag:IYibPi1Kmvn42uVwvPSSPQ==,type:str]
            #ENC[AES256_GCM,data:Sf9GQGfb+4s7wX8AUuxqBhOw5cl2DC5PbpmlTZEnII9BZ3nNRwKJSWc=,iv:yWdQFBepT/vNxFK0jMhpAc4HerpbVauRZxkzGN3OSms=,tag:ZeK7VHifp+aqjDY3B24LxA==,type:comment]
            serviceAccountFilePath: ENC[AES256_GCM,data:/KApiW1XCY+IABy1FkIDAfpGpUsZr5o5r4dgjlYTRQ==,iv:v/Ib7woaLi9bRkghRWXFWnnknwm+auu9U7yCWHqoRG0=,tag:dGAhZT2NOg1wSDNSeWMgLA==,type:str]
            adminEmail: ENC[AES256_GCM,data:pP9Qa9XNouDD3dM2QVg8raE=,iv:tj7FMHBHtM2eZAn/KBNVqkB/fL2qWau/PalBjCvP6gI=,tag:CoV+hskfBlwmTxjM1nBxRA==,type:str]
  #ENC[AES256_GCM,data:K/WgvSvL7/OOzIA0IHOk5ASUtK0=,iv:pZjsWXceGubb6MgfnPYvX0NnszPj84VXYDoGVtaRjx4=,tag:8uMk0zY/G3sg4WwOyCRnJg==,type:comment]
  ingress:
    useTls: ENC[AES256_GCM,data:TF5wKw==,iv:4p/1WvvbndBemhBXhQEUl0MRn14H9tBtteoiU2LhDcg=,tag:s7lZtl/BV288QkitUMZlAA==,type:bool]
    ui:
      enabled: ENC[AES256_GCM,data:kLwG5w==,iv:KQ9l0QQSEFrNMOjg2ARFCT0zD5Rc9FAGH54e835JzTk=,tag:NJOdBre8t2i8Ct/8OrRf3A==,type:bool]
      domain: ENC[AES256_GCM,data:YbP6QRfuq4xD53Pxg2wt239xerdgJJFo0w==,iv:a98X8txq+Hukc8QMS97bRijAmX9UIX6UkojUAgemUWM=,tag:F4hlFpyaxcdAob8JwR5z/Q==,type:str]
      path: ENC[AES256_GCM,data:yw==,iv:awR3LfxatqqfrUv5r4LRL3K+EvC0cqEq+uaxUo4orVI=,tag:PxEN3/qf+wMNkaclSsXVXQ==,type:str]
      pathType: ENC[AES256_GCM,data:7am92NKN,iv:BHilF4Z0PyQgPltV1gB1orTpUXutQl/lRRk6MwXJMmg=,tag:ERykKEpuOPG+9RLFsAWDpw==,type:str]
      tlsSecretName: ENC[AES256_GCM,data:94uWF/64lj108JcT4knk/V5NssZ0PeE=,iv:aNkpXrLvMpLzHsrZFyNxRUHM24L04TVMqHnYYMIH7p8=,tag:YHMBRj1td6nNJTMNTU/kKQ==,type:str]
      annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:wcvspWrgmvfycUFwnQfJ8w==,iv:SDVVvkfTRoq/bvmTI95pJAdqqwuKzzXziWmfVTg/y8w=,tag:w58jiQiB9YiQVW6QF85h/A==,type:str]
    api:
      enabled: ENC[AES256_GCM,data:rpsR+Q==,iv:ew186+B1zkzbur0ly7f8vsWLPgG7Rp8rlALQI0Ytk9M=,tag:TIz4EIt8gsn0AfUBZ9G2xA==,type:bool]
      domain: ENC[AES256_GCM,data:TrLmsDJUEpiArdJsEK73sUrg4HWqZjKo1mI=,iv:rb4rVDtLqz2NlSbSAxwRI/A5xYmgx8RABgB8VWSDiP8=,tag:FawO8sN6cE8pZXyWODj4KA==,type:str]
      path: ENC[AES256_GCM,data:yQ==,iv:4km0ewbFy6xp4s9ceeYoZ6SCJzF9Qfj267SBbj6NDPo=,tag:tFZUGok4hCFpp9KCB4Z1bA==,type:str]
      pathType: ENC[AES256_GCM,data:S6RQ+rKp,iv:1gvhdj8mKFmfDIU1EiJ35Fs/FdWGr95A1H3Ag9hVt/o=,tag:R2MWDg7oxxwR+3k5k0w8cQ==,type:str]
      tlsSecretName: ENC[AES256_GCM,data:fTnDprpa3UN8kVsRjcqAK7zzWm0/0EpR,iv:QjPQfI8GfDID5FRh/1Eb9bNYRjiwuUwXEBIGdPhNkmQ=,tag:EJzw3myMMHykmj8b/djVTw==,type:str]
      annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:k1RofgPRXVuaRVZwXJNebw==,iv:frgePjtSmOC9aukaJznz3y7vhbWw8DUziwM0jM7NekA=,tag:2/qWITxLIp/3wSZkL5NNMA==,type:str]
    registry:
      enabled: ENC[AES256_GCM,data:nvKvXw==,iv:NBIvIOfgPb6w4eV7jQPKxlT6iqkaDiVcvdDHPVHSVXA=,tag:Pl3mW2YwmipZrvavS7Tgcw==,type:bool]
      domain: ENC[AES256_GCM,data:9hxzPOh1tP1UhJYkAtk84RYFbNaxi6zNF5E=,iv:5aItT99F9KvLLZpVYYoWWnIj0Qq7XTo0J40HrvrKSHg=,tag:973yesIfkUut/2ltyy7k+g==,type:str]
      path: ENC[AES256_GCM,data:fQ==,iv:/tm4kJmpGlV+92JeIeshTHr38KXDaCiSgOVFkadFy80=,tag:gCPy0MRfJkX73gA5+VS3XA==,type:str]
      pathType: ENC[AES256_GCM,data:8PURLzFZ,iv:2NR9lrDQAwKD70cw2GxW55DxHpOQCo8z5aZ6Z7rxAPA=,tag:LBsXO5SQAnpb8tzde5u+XQ==,type:str]
      tlsSecretName: ENC[AES256_GCM,data:SyTW69pheuLJ1AOL2WeHcavEQPgYJgUp,iv:LossW2OhfeGwMNdqqHuf6gXkzb/7s9nLR95koqbE/K0=,tag:hg5y1G6jMJMmWCQfXaWyyA==,type:str]
      annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:KhSKffwVLYSVU0TWdH5pdw==,iv:btlW8nw72cskGDtPv5fRLVKTJk5evm0vQGzeteC9rro=,tag:OAet79A6ICQoL5b8MBviiw==,type:str]
    dex:
      enabled: ENC[AES256_GCM,data:vRzqzA==,iv:lKNEp8aubNvig7gGlaunZE9KebfetwWMxohG0qXgdDE=,tag:Xikt5LHkytRIuErjfraPAQ==,type:bool]
      path: ENC[AES256_GCM,data:PKpwtlM=,iv:X+DdKFq6Uk5Q7LIGmL+JZ5/0EY0eAhcwK1Hd6O292QQ=,tag:rO6ijoW/cYd4CctzFwwg4g==,type:str]
      pathType: ENC[AES256_GCM,data:CALgA38q,iv:ZL0YZTnYsqZBHtxci7y2OACceOiPHLotN08To8MPqeA=,tag:wZ6WEnnotgclTr+oc/urYQ==,type:str]
      annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:v0N0kdfAf8CI1s+U33tlLg==,iv:r6TzJD9ErvKIDLrTG2bdWGqisRRSv+IsVwzBzGsGTHQ=,tag:BK7ky0PiHgfiHNSDt6jFMQ==,type:str]
postgresql:
  primary:
    persistence:
      annotations:
        # sops:enc
        volume.kubernetes.io/selected-node: ENC[AES256_GCM,data:2uxj7OX4t8lpljCbZ42lnVXV9KemnkUoM5ileeM=,iv:jIsNfUczqizwWpnF619992HQT5gJJHw8GRMvXMzD3mU=,tag:aZyUcdUBrxqZ4lS5VsxVIw==,type:str]
  auth:
    username: terrakube
    # sops:enc
    password: ENC[AES256_GCM,data:PiPUn9VhSDpAORT26bffiu5AyGBM67hcZhvpXT2UHnUrXnWRNkxHq2UnhETrG2BBXCgwVqoo0QjAmgox/9KVVA==,iv:Xd6ckFOnwu0ua6eTKgpqFOJATQxwVG6QsdAbchc/xHw=,tag:ZokMUNi3X83WvzXPIJO+Bg==,type:str]
    database: terrakube
redis:
  architecture: standalone
  master:
    persistence:
      annotations:
        # sops:enc
        volume.kubernetes.io/selected-node: ENC[AES256_GCM,data:P7sbj4ftTHLM6VrNjN8/ymUX562v0gHgqZSU3po=,iv:IIqy8bWFLbsgy5TGcBctXrpwtfu9DhGRl3ujFcxppMU=,tag:MtnBAv9oozSeORM5w1fagA==,type:str]
  auth:
    enabled: false
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRlFVdEt3b0hPc1Nwem5o
        cHN2MzJ2MHZybzBGd3dGTzNvSDZ0N0o5NkVNCnpJVDBzVFBqblQ5UHFudHNKY0lz
        czE3UXRCdVFVa1pOa29nRUpvaC9MdmsKLS0tIFhWd0Z0U3FOcWJLT3g3OHVDT25x
        UTRCUHZNOUt0TDhlZm85Y0pnWW8zajgKFrw2ydDQR9dr+4ZdEKns3OWvTNeY78zF
        HTMRfqsiqdmwfxCNPDGgjb9e2RkEyelmogCXPC6jywTB1whZ3l7cBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-28T00:08:37Z"
  mac: ENC[AES256_GCM,data:9YESNcbii1B49pzgg4/3efTyDhjM/gFoXaLhwWhc5r6aWcLxZtludu9IW+lEwDOiKp8qVTAv1GS7DO8cJ5fFhj4XwwXqVwfpJ8vzScQ2dhSp3cu4dRt5YPfyysmATB5M0H9J8K6r4hPA6CZsElotq9v38CTU5AIDy7fPtftuRIg=,iv:8VNJ4Ca+wnzq/5YOl7gjdQ7WNEtIOLS1Dqpke2FIAxg=,tag:/Bx+J/rQk6/aU6JTYDo6xQ==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.2
