kube-prometheus-stack:
    grafana:
        enabled: false
    prometheus:
        prometheusSpec:
            retention: 10y
            storageSpec:
                volumeClaimTemplate:
                    spec:
                        storageClassName: local-path
                        resources:
                            requests:
                                storage: 40Gi
            additionalScrapeConfigs:
                - job_name: node-exporter
                  scrape_interval: 15s
                  static_configs:
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:DSvoHbPKuD8uKK1WbBPSvCnD1jdbQiDQ+UfiLoF3kbXvVPM=,iv:CkOm1aF11uOQ30kVLegYopS/4ZVU4Iz+O9zREramAyI=,tag:8Xy9LTFKoOWanD1wzQYrLA==,type:str]
                      labels:
                        os: ubuntu
                        type: hardware
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:tC1X1QPhXVslCU75WEm09IM=,iv:O5EmnawrY9nW8H4/E3OOhOddp8+II/OT7+RH2Nha3nU=,tag:RMEXYKa8TYK/GRaMPwOv8w==,type:str]
                      labels:
                        os: vyos
                        type: hardware
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:Rm+yB53J3y+nSdRT0vrv9l7RrpozCuFiffYeVhVk+SkXQQ==,iv:evmAlTROtwzaLdSV+Ir2f23DJNkuYLihRal13icJAv8=,tag:GRxFRBCLjHNrz4D755JCAQ==,type:str]
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:DeKOzyQQoMNQTUu5Nyqo,iv:ymLRbuGmjQQnk2oUWRjvLg57p0lnEWQ1mWmHRuexhow=,tag:N5emAyDVDJBFupT7bF18Uw==,type:str]
                      labels:
                        os: vyos
                        type: virtual
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:caSskLpXzUsiEAcKSVXdzfAACz9xfGYwTZGQF1SxLIgRyQ==,iv:vCcyIUCqqYyGxvvkWXP9Bh1hgk3mUuo7Xw3npOhZZ80=,tag:BhtHy2mbGgmDMBw5fQJDEA==,type:str]
    prometheus-node-exporter:
        extraArgs:
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|run/.+)($|/)
            - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
            - --collector.netdev.device-exclude=^(lxc.+)$
            - --no-collector.arp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaVNZOXpaalpKa01McjZq
            NDFnM3FKbFozb0hVL0tRSXQ2SE5QajcvM3kwCjRHWVloQVNXTHhCTXNzSFB0ajdX
            T2ZhVDBJQmIrdWFpWEhUZFhwNFAvek0KLS0tIFVHa0tEUmFwU1BxelFjSDZ2d2Y5
            T0R5TmoxNFBMWkZqTkFsSDhpZC9BMk0KXv1tZkKlQeItQ2HXI7gXJrZdBDKusLNE
            KWAOjpw5oxH/qo19H5+h1WpeR3Jp0cgxLZuHyc43Q75a2Yv6GiD5uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T05:32:08Z"
    mac: ENC[AES256_GCM,data:NJLfk4xAYRxZcClU33jdNhG/zp/hYMBhIcR5jgIUumPbudE5M/6UaeuYC7+sIMw0c0pyGb3mTMNSBLRGhUVEVqNd+Epb8u3cVioGJBu7ybdgK3poOqVGanK0UnLjmSj8L2u4bqe+1gEkf6dXzsz8SzZftRIVc26L9aO8zX5uzCE=,iv:p1O59vq3C2sp4mlyOJ9Ho+qxV5J0Ib88kkttnGtYKSA=,tag:YtTLlCiLan5x+a5C0m5TyQ==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
