kube-prometheus-stack:
    grafana:
        enabled: false
    prometheus:
        prometheusSpec:
            retention: 10y
            # https://github.com/prometheus-community/helm-charts/issues/106#issuecomment-700847774
            # https://github.com/prometheus-community/helm-charts/issues/2323#issuecomment-1612551019
            # discover any podMonitor / serviceMonitor in any namespace
            podMonitorNamespaceSelector:
                matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: Exists
            podMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            ruleNamespaceSelector:
                matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: Exists
            ruleSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector:
                matchExpressions:
                    - key: kubernetes.io/metadata.name
                      operator: Exists
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
            storageSpec:
                volumeClaimTemplate:
                    spec:
                        storageClassName: local-path
                        resources:
                            requests:
                                storage: 40Gi
            additionalScrapeConfigs:
                - job_name: node-exporter
                  scrape_interval: 15s
                  static_configs:
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:dkCGfgKGSmngugd2UnWVzVsVG5I7tzXd8WU90eZILTgwmME=,iv:7fldMkKFoDi42YRQUwCfuGjculQSagCpiHWgwQ2M1Ng=,tag:cdlAk60dw3HYHDbSU6I/Sw==,type:str]
                      labels:
                        os: ubuntu
                        type: hardware
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:RD7xcVfxt7a4VEPxLySswSU=,iv:bQ0QP3OK73ZHUNCC6OArF7nWZorijpXrwR8nxauac+s=,tag:cdhL515XnNAd+NhW9HjJAg==,type:str]
                      labels:
                        os: vyos
                        type: hardware
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:3Ai+Ch+d6zL14eB56OCQU6OxHYHN64KgDy5mfgVN2Yz3HQ==,iv:89oiz3JCdMrfb7+Wfzqtpuoiyfz6803tKaPc0aZiJcI=,tag:2IUxMjIaeUaVClEQbj+yrw==,type:str]
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:CeGwbJhddlLoWo7QHLYF,iv:49YjE4A6IUtN14vxmQ0ioA99YumwU25voqcyc2jAGGU=,tag:+XENe4FAKywxiIxAutHuVQ==,type:str]
                      labels:
                        os: vyos
                        type: virtual
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:jW22f7/Y95oEgu2b4kLbUiJwGFaasiiH45K+FmxQJ76Grg==,iv:QXpDVw/k+zfizZsnnHPgvplc7u7m6YA2VsJMdJ861ic=,tag:bNy903QiKIyoRggJYd+vsg==,type:str]
    prometheus-node-exporter:
        extraArgs:
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|run/.+)($|/)
            - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
            - --collector.netdev.device-exclude=^(lxc.+)$
            - --no-collector.arp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdHQ2d1NQOWo2dVdyMlo2
            Um1yZ1VWODZYVk8rNDlxSk5xUnV3cjllWVdvCkdoWlpERG5pdmNzd0V0eVMyejZj
            N3V0UHBCOGRJUFltNVRvM2t5MldyMXMKLS0tIFpYNDZ2QkZEcHF6S2VjOWp4L3FM
            a2paSGkrSk1ocUt2QldnaHRrZm42RlEKft9nZCxAzMd0jSVQts/DBBMrDrj0pyf+
            bqPPCtUHVCY7lLhuIMQAesqOSIl8zTbmuUQCh/CIv95biKYfKiwG5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T06:25:09Z"
    mac: ENC[AES256_GCM,data:9HclCkLXCtbukPu3UXeOBrkm9mwZUNzw+shcY+qxr+TaJRSzIpiQSj98XAhFkZxKWKa/O4xlaipYK0wkvdquvjEMvIqPhgKtPHtXNO1p3XOofOZwZFz9MJiWIlQf/vPOQy17eCfApEtuT0j7bYm+q9rsQ7Vsj8+nBFFZvTbtrVc=,iv:+dfwx2C71evDkd7PNwPkLsAhEsYIDF0KttlZDcuJD78=,tag:bUOFLK5X1vTJDod3hIYGWQ==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
