kube-prometheus-stack:
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      retention: 10y
      # https://github.com/prometheus-community/helm-charts/issues/106#issuecomment-700847774
      # https://github.com/prometheus-community/helm-charts/issues/2323#issuecomment-1612551019
      # discover any podMonitor / serviceMonitor in any namespace
      podMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      ruleNamespaceSelector: {}
      ruleSelector: {}
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            resources:
              requests:
                storage: 40Gi
      additionalScrapeConfigs:
        - job_name: node-exporter
          scrape_interval: 15s
          static_configs:
            - targets:
                # sops:enc
                - ENC[AES256_GCM,data:mK3HBfM9MBvMvNKMpNOGXjALtgFXzJUAf8SmGWlIzy8ChbI=,iv:HBSG9NwB+Z0SvG92g2s+K4iCjMiN6kKosDd+wZMN5vY=,tag:kwWQ0UClzawmPj5O5/YgUw==,type:str]
              labels:
                os: ubuntu
                type: hardware
            - targets:
                # sops:enc
                - ENC[AES256_GCM,data:T7YzrEk/SR/HvCoGA6/eNAI=,iv:z2gRjWeOCjWTiye+uN2HR4AG+RDOqS08rrigMxsVMb0=,tag:ZlJjJ/enxXeeI3o13g/7sg==,type:str]
              labels:
                os: vyos
                type: hardware
                # sops:enc
                hostname: ENC[AES256_GCM,data:a2/cpThq7M9o0Zjw49iG+E3/mNe0jKD+BN2BcUCQZ5Rapg==,iv:/Ql2lCb0GNk0G2t+2FRU/g5Ze6OCQ9s1zEtZqVtZ6wc=,tag:j1MM27OAipnRFlY47cKWbg==,type:str]
            - targets:
                # sops:enc
                - ENC[AES256_GCM,data:k+9bZ/uvrgX5u6Mr/o8M,iv:P4DZO2EXuLOODSKhhjLOl9DcllBBSoQTj8t2SNTfRt8=,tag:MKjuMjK12tyHacb+cH5PnA==,type:str]
              labels:
                os: vyos
                type: virtual
                # sops:enc
                hostname: ENC[AES256_GCM,data:2KmRX6+W7jeVOg1ir+NnWuS9kjew4N0jCRmy7Edk34EMSQ==,iv:OlLnLiA4j0ue5gDppDoEfvY40LRTQ6QC5VFbrEsXimc=,tag:lpP9GBdpRw93b7brc+dZmw==,type:str]
            - targets:
                # sops:enc
                - ENC[AES256_GCM,data:5ZGVBABLVpteCoMaZNsmFw==,iv:e1oJnMPJn8a/xYi5BSxSakiAWG7kpVRPwXFl7mkwQQc=,tag:1rn6IKuZBsdJa/PKyCq7eQ==,type:str]
              labels:
                os: debian
                type: virtual
                # sops:enc
                hostname: ENC[AES256_GCM,data:RxMue5Vo+knkfkjRt+cYdyyUduEj2hM7zaj7qhapqJI=,iv:j3yYrTTXSWw0+dykJFWjbScOUt6uUDcXxvqrBXAuYXY=,tag:nRY+FTkQYwggc9fviYZgoA==,type:str]
  prometheus-node-exporter:
    extraArgs:
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|run/.+)($|/)
      - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
      - --collector.netdev.device-exclude=^(lxc.+)$
      - --no-collector.arp
sops:
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGxqSTJBaTNBbnRQQ3hW
        eHh3eTFyQ2RvV0daUUEzYmUrU0NhQzhHQnlZCmQvZ3Q5ZnVLVXEvb2FCelcrMXJ4
        NUJlRHR2TE96SDhtVnBZRDlTdnM5V00KLS0tIDlGT0tMNWtJL3ltcXIrRmN6MWxM
        Vk1sVFo1cTRrZUltYlgrZTZxMHA4bDQKF7VmYIwV79VdgCTCxHQXIHAPy7tyJBgg
        S6+0OC9J0l8E3J80wpGVf/Tu0FZKSyySrvcUl3Q9Ym0VX+YL+0znKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-25T20:26:11Z"
  mac: ENC[AES256_GCM,data:RQ7mV/NKU8L1dA5ZePAq5B8l+XVALEwc/u6IjA05jQEXXRgTFgdZQS5puilBHpx67CHTxVWcOSg3UX7o91X1Bp4pCaDSTvwznC7Nhf7pE8A4PKXFhSjc6iQf/pGjhHAMFxlOJjXXLtXjPSXEDY3/FrcT6F9375nXzfIkicbgBh8=,iv:8DVtsst5hST81a3QUU9sBr4jS4DPORHDdD1+tIO+C+Y=,tag:iufq5HLbNw8izh2YIWnQYg==,type:str]
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.10.1
