kube-prometheus-stack:
    grafana:
        enabled: false
    prometheus:
        prometheusSpec:
            retention: 10y
            # https://github.com/prometheus-community/helm-charts/issues/106#issuecomment-700847774
            # discover any podMonitor / serviceMonitor in any namespace
            podMonitorNamespaceSelector:
                any: true
            podMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            ruleNamespaceSelector:
                any: true
            ruleSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector:
                any: true
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
            storageSpec:
                volumeClaimTemplate:
                    spec:
                        storageClassName: local-path
                        resources:
                            requests:
                                storage: 40Gi
            additionalScrapeConfigs:
                - job_name: node-exporter
                  scrape_interval: 15s
                  static_configs:
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:kDEmB1vUpHGn2cKHMaKk0VpTta6U2y6ybbQpXkWuDRo+a3U=,iv:owTwKWPovQsj0s2huztGAAXGsoGQKmNZ/x7qvxPfrkE=,tag:pwhiGRFIydzW+/OvIU+DAQ==,type:str]
                      labels:
                        os: ubuntu
                        type: hardware
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:oP1tjsQFKoQj9fJGTBX91Zs=,iv:OhX1yD24gBXM64IqILulznrbbaaiLVzsuLTMDMOC2Vk=,tag:T+ZRJGUhdMtfk7nc2A5Chg==,type:str]
                      labels:
                        os: vyos
                        type: hardware
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:Fh2yQz0A5MklgX9Thw8NYFlqux0wTPYa6gyJp8cpaH2jVw==,iv:HHQ16EV7fYQ42hptqeL7K/E1MVZyLlRQaP0I1xihD1o=,tag:eyMCcoQiVbj7j/DYUJIacA==,type:str]
                    - targets:
                        # sops:enc
                        - ENC[AES256_GCM,data:w0x5D/feBFzUG/hyB3Tx,iv:okZYOajYnxJ+UmhMpMVQtMpvyS0NB1TfBbl3Xcd2tfo=,tag:UBUNwqx8bNl7PFg2KTrtmQ==,type:str]
                      labels:
                        os: vyos
                        type: virtual
                        # sops:enc
                        hostname: ENC[AES256_GCM,data:HDXTEkPGDswXQSh/OSlhabsnpKi7zBpuQ/Cfd7DTeEo6hA==,iv:J86DAA//bmZTIM0EsoamwI+vFtH+dguc8JcO/TTf+i4=,tag:hHfmKhBagnxTviD2IH7rwA==,type:str]
    prometheus-node-exporter:
        extraArgs:
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|run/.+)($|/)
            - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
            - --collector.netdev.device-exclude=^(lxc.+)$
            - --no-collector.arp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDBmbGVtUC9EQnRmdnhS
            dHN5K2hwdytOM3NBSEFHS1F2ZmQ1MTlhVkUwCmlEeGozdDJ3SnRnYmNDd0d5SkYy
            QzhKa2M0ZVMzaTRVU05vS2RXVDl3VDQKLS0tIDU5UCtLQ2NtZ3o4OWxmVTkzeDFZ
            bm1oVW5OcFQrTklYOVNVc1ozRTlXSDgKAFwhZPEKh+bt/QjMdM2hAWJyHDTqVadp
            z0PwpF9TbApPqFre0vPw7KJUB8ZXgTzIF3kzheyOPZ5VWOETFIvQBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T06:15:35Z"
    mac: ENC[AES256_GCM,data:Vk96z/83BAGwZPV82dTek/4bB8h4v5kauJhZIHycBL7L3ZLbhPH1Vm7YV7JkgqZMtW7KERP9rHASXTzrkE3uIeKjqHta4CEJ6os3d+kr5amd6PZhYlLxypmB8dJ5uS9/wW8KIHfikJ8NiQcSNqDTa2ab+tHYdjq53MxlgZMDHDE=,iv:zo1hFOx6uL9+JBJnk4+2ZYKBqxY8vyLEdOT1T2pRzQg=,tag:1yezbrSalz6brmwjTEWmLQ==,type:str]
    pgp: []
    encrypted_comment_regex: sops:enc
    mac_only_encrypted: true
    version: 3.9.0
