---
kubernetes-ingress:
  controller:
    replicaCount: 1
    ingressClass: false
    ingressClassResource:
      default: true
    config:
      ssl-redirect-port: "443"

    service:
      type: LoadBalancer
      loadBalancerClass: io.cilium/node
      externalTrafficPolicy: Cluster
