---
kubernetes-ingress:
  controller:
    replicaCount: 1
    ingressClass: null
    ingressClassResource:
      default: true

    service:
      type: LoadBalancer
      loadBalancerClass: io.cilium/node
      externalTrafficPolicy: Cluster
