windmill:
  postgresql:
    auth:
      # sops:enc
      postgresPassword: ENC[AES256_GCM,data:NjtRinNkHq00bQRTPEK0HIh+O+JsZqDEcjlAqi3e52JgGhSTZQaCE4JcgVllqZKhykss0R517qZitFcxicwSaA==,iv:/z8CvCmnMxAbDXG1V474xglM6v/QPaDRULXIm6syhLk=,tag:6w4JadAwXmhEyZVJHQthgg==,type:str]
  windmill:
    # sops:enc
    databaseUrl: ENC[AES256_GCM,data:aewJWJdnUHDekPo/JvVjeQRxau7Zqx3BLOFBd0Pvx7b+UukvJFBBhjPO4Nc7EJ2wzPaely1GOCYVJ7bthpOrGfSaqvPrH2FHpOSVppdQ6OKjPa9AE+csccaPQTKQqllUhIc5RQEtvpAwLE35s0a+bIh8jluSU96MqvtSeTyzXxmUbWq7VA75,iv:9vHcjaNzbemN46Duhq5CtddYiufUeDqWJeaKL/CI1jk=,tag:pSe3WIqBpwnwFEkkLh6YkA==,type:str]
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:nZslpXxnV6eyK6rQ3g8Gb2iP8cUU,iv:rIHFB24QJEgulaDOC18MEPdkynb+pkskI00fwUKEuBQ=,tag:pD8HesCCAvB+6Mu4A3mqCA==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:Y3RgNk4vdCxEsNqJmbglD3OlEX8A,iv:huLa5HIbidmgyzkSRg4YqJ68EtuNf5xZI/pRd8+FRAo=,tag:eSU+jec3rIeCc6GS3vi9cw==,type:str]
        secretName: windmill-cert
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ3EzSlR3QXhiY2RCVm0v
        NndPOHYwWGs5WVBtVjA3U0MyY2Rhc1JwZlIwClkvcVZqanZLVU1STDlFMkQwUTZW
        a1B3anQvNk4yQ0x1VitiMDZqVURWS3cKLS0tIFAzODQ5d3RqREJTVmRjUXBPYWFQ
        UlBIRVJySVdubk9GdU8yL09iUDNVQ1UKWIzHgH3Sc/0DcGm0Etnb7WV5NjNv+erU
        UFo74a4IoynNumgcJILImNHOSOGJhVhD+9a8k3YU26lZhuIE/SeukQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-06T08:26:13Z"
  mac: ENC[AES256_GCM,data:mQ98PWfZtyU7umuP0STWKSRe8BpWszX7DWAXP9NNMk14xEUuzLP4WgAllV7ivMjbRxClQ7k4dxUCf2O7D6+2t+21ljgAtogJYb6UeYE+zuAOpJxQKfPnkIoHbMfMnt2FRlShKFZfEa/bToNBJ8TOnG6/FeMT6xjWpsD76cnEPv0=,iv:Pp+AovHnHhpPSOGKvoiNYcQsIwmUKjuQufQkoqkphZE=,tag:Wot3DI0Cl0seyRFEeZUgsA==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.0
