windmill:
  postgresql:
    primary:
      resources: {}
    auth:
      # sops:enc
      postgresPassword: ENC[AES256_GCM,data:aIxPFYCFSsl82+UXmrP4bxqD5vjcQTDQd06kf/iiZolfoeQrAH/IyNCpfIfVt1KzNqkEuILLvFMTnB8vg0saww==,iv:y6p04rqq5tPYMxPA0FYa+R5K9UeIi7RRa0nSXLyz+ao=,tag:f5Zjli7MnBQxdXi9ZQLbMw==,type:str]
  windmill:
    app:
      resources: {}
    appReplicas: 1
    lspReplicas: 1
    # sops:enc
    databaseUrl: ENC[AES256_GCM,data:lhYxGuA+FGRhIS39X/jpnB+rnpgNO1xo+ex2TOZSA3TvlnbXJvlLJGs5b8te+DZ6tURwSHw1kZbuUxX+wLGIGDw7+9eUFjojGKcKAI/4r5dGQ1Lecdnw0+CCRGWk5IXc0v0M/Zdb2aDk+uzmGFBHSJQpUmYnPNJLetpcPmDoVbQ2,iv:EbmT4EyBhP2EqI3Qzxdb4Og+66at1CCZH/ltxLm8AOA=,tag:SLXInrOpO8vkpRY+ymeQqQ==,type:str]
    # sops:enc
    baseDomain: ENC[AES256_GCM,data:kcvvoDS4u/8ZX8ErgURGbuFaKbUn,iv:PEE6jonhXmU0viw/3zgTZe9F79+9N4+w5+GkbEqGXcE=,tag:ccU2EWteLtyUx9Liw9Dkxw==,type:str]
    baseProtocol: https
    # copied due to array :(
    workerGroups:
      # workers configuration
      # The default worker group
      - name: default
        replicas: 1
        # -- Annotations to apply to the pods
        annotations: {}
        # -- If a job is being ran, the container will wait for it to finish before terminating until this grace period
        terminationGracePeriodSeconds: 300
        # -- Labels to apply to the pods
        labels: {}
        # -- Node selector to use for scheduling the pods
        nodeSelector: {}
        # -- Tolerations to apply to the pods
        tolerations: []
        # -- Security context to apply to the container
        podSecurityContext:
          # -- run as user. The default is 0 for root user
          runAsUser: 0
          # -- run explicitly as a non-root user. The default is false.
          runAsNonRoot: false
        # -- Security context to apply to the pod
        containerSecurityContext: {}
        # -- Affinity rules to apply to the pods
        affinity: {}
        # -- Resource limits and requests for the pods
        resources: {}
        # -- Extra environment variables to apply to the pods
        extraEnv: []
        # -- Extra sidecar containers
        extraContainers: []
        mode: worker
        # -- Init containers
        initContainers: []
        volumes: []
        volumeMounts: []
        # -- command override
        command: []
      - name: native
        replicas: 1
        # -- Annotations to apply to the pods
        annotations: {}
        # -- Labels to apply to the pods
        labels: {}
        # -- Node selector to use for scheduling the pods
        nodeSelector: {}
        # -- Tolerations to apply to the pods
        tolerations: []
        # -- Security context to apply to the container
        podSecurityContext:
          # -- run as user. The default is 0 for root user
          runAsUser: 0
          # -- run explicitly as a non-root user. The default is false.
          runAsNonRoot: false
        # -- Security context to apply to the pod
        containerSecurityContext: {}
        # -- Affinity rules to apply to the pods
        affinity: {}
        # -- Resource limits and requests for the pods
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
        # -- Extra environment variables to apply to the pods
        extraEnv:
          - name: NUM_WORKERS
            value: "8"
          - name: SLEEP_QUEUE
            value: "200"
        # -- Extra sidecar containers
        extraContainers: []
        mode: worker
        volumes: []
        volumeMounts: []
      - name: gpu
        replicas: 0
        # -- Annotations to apply to the pods
        annotations: {}
        # -- Labels to apply to the pods
        labels: {}
        # -- Node selector to use for scheduling the pods
        nodeSelector: {}
        # -- Tolerations to apply to the pods
        tolerations: []
        # -- Security context to apply to the container
        podSecurityContext:
          # -- run as user. The default is 0 for root user
          runAsUser: 0
          # -- run explicitly as a non-root user. The default is false.
          runAsNonRoot: false
        # -- Security context to apply to the pod
        containerSecurityContext: {}
        # -- Affinity rules to apply to the pods
        affinity: {}
        # -- Resource limits and requests for the pods
        resources: {}
        # -- Extra environment variables to apply to the pods
        extraEnv: []
        # -- Extra sidecar containers
        extraContainers: []
        mode: worker
        volumes: []
        volumeMounts: []
        # -- command override
        command: []
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      # sops:enc
      - ENC[AES256_GCM,data:AobSvLtLQjDd+rgdEEgGl+DRr7d1,iv:2/Eg1Ho8epDRZAnuK59tZyq1TviDa52jMmVOFHvocN4=,tag:j1rhQQb02hJf6sal8Ie8xA==,type:str]
    tls:
      - hosts:
          # sops:enc
          - ENC[AES256_GCM,data:0Q8w8yaCC8wYCs8fi9drJ855bTPy,iv:9z+V88RT8FeyuwbhcFfztfvF1QLEMNEPRnUOexfw7Sw=,tag:OTkXxsguiODgh2ExX6AL9Q==,type:str]
        secretName: windmill-cert
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18xjyppfrwl82jdltqtjxy8n86qlee24h5tftpgrjzp7r9pn5ecmss4pd7k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV0Q2Zktza2p6djBzNUFu
        Y2FuUXliVWwrR0hiMVZNRndwMklWbkF4YTFvClBDdHhpY3NiamZneHZNZWFsbkxU
        M1BaTStUQTYxd2E0MDR3cUd4YnJ5MHcKLS0tIHpkcGI0VTYxZ3A2WGdDNzBNcVlU
        YndSd0dwU1J1Wm1TMjhCaXhtZklUUjQKj41WNOaoJD2Btxhe5tna3BPTjwOujm0m
        bTfv0cem9+5a6nqCl/2uZS7koHncDhQnDdmu1RAXnys5KYunl7LehA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-10-06T13:24:33Z"
  mac: ENC[AES256_GCM,data:0eBxBdrxDdwWXQOoNpgSCSs/NKdUt587lPxQcUtgdDUGQ+H6j06rJ9PNDK/9v9rQoTvXM9zztcUNbI+y3LjP62yKDQOjfBOQV3q1br98g8+MOyThsiyoMzw3DoruCIhMJUxdRoz3ft4HiWiedUrx46Ibfa8ie5uzPhTWeHZORsI=,iv:VFGiqLhBi9JrLsLVOAU/YLVhd/DoBbJO27xYIuofiNo=,tag:qCC24xGZRvB6FMqujYlRGw==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.9.0
