cilium:
  operator:
    replicas: 1

  envoy:
    enabled: false

  # https://docs.cilium.io/en/latest/network/node-ipam/
  # this requires cilium 1.16.0 which is not stable yet
  nodeIPAM:
    enabled: true

  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: 100.64.0.0/16
      clusterPoolIPv4MaskSize: 22

  # this makes us see the real client IPs
  kubeProxyReplacement: true
